// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: ctap/ctap.proto

package ctap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ctap_Ctap_FullMethodName = "/ctap.Ctap/Ctap"
)

// CtapClient is the client API for Ctap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CtapClient interface {
	Ctap(ctx context.Context, in *CtapRequest, opts ...grpc.CallOption) (*CtapResponse, error)
}

type ctapClient struct {
	cc grpc.ClientConnInterface
}

func NewCtapClient(cc grpc.ClientConnInterface) CtapClient {
	return &ctapClient{cc}
}

func (c *ctapClient) Ctap(ctx context.Context, in *CtapRequest, opts ...grpc.CallOption) (*CtapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CtapResponse)
	err := c.cc.Invoke(ctx, Ctap_Ctap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CtapServer is the server API for Ctap service.
// All implementations must embed UnimplementedCtapServer
// for forward compatibility.
type CtapServer interface {
	Ctap(context.Context, *CtapRequest) (*CtapResponse, error)
	mustEmbedUnimplementedCtapServer()
}

// UnimplementedCtapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCtapServer struct{}

func (UnimplementedCtapServer) Ctap(context.Context, *CtapRequest) (*CtapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ctap not implemented")
}
func (UnimplementedCtapServer) mustEmbedUnimplementedCtapServer() {}
func (UnimplementedCtapServer) testEmbeddedByValue()              {}

// UnsafeCtapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CtapServer will
// result in compilation errors.
type UnsafeCtapServer interface {
	mustEmbedUnimplementedCtapServer()
}

func RegisterCtapServer(s grpc.ServiceRegistrar, srv CtapServer) {
	// If the following call panics, it indicates UnimplementedCtapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ctap_ServiceDesc, srv)
}

func _Ctap_Ctap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CtapServer).Ctap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ctap_Ctap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CtapServer).Ctap(ctx, req.(*CtapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ctap_ServiceDesc is the grpc.ServiceDesc for Ctap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ctap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ctap.Ctap",
	HandlerType: (*CtapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ctap",
			Handler:    _Ctap_Ctap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ctap/ctap.proto",
}
