// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ctap/ctap.proto

package ctap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CtapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           string                 `protobuf:"bytes,1,opt,name=Req,proto3" json:"Req,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtapRequest) Reset() {
	*x = CtapRequest{}
	mi := &file_ctap_ctap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtapRequest) ProtoMessage() {}

func (x *CtapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctap_ctap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtapRequest.ProtoReflect.Descriptor instead.
func (*CtapRequest) Descriptor() ([]byte, []int) {
	return file_ctap_ctap_proto_rawDescGZIP(), []int{0}
}

func (x *CtapRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

func (x *CtapRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CtapRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CtapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtapResponse) Reset() {
	*x = CtapResponse{}
	mi := &file_ctap_ctap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtapResponse) ProtoMessage() {}

func (x *CtapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctap_ctap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtapResponse.ProtoReflect.Descriptor instead.
func (*CtapResponse) Descriptor() ([]byte, []int) {
	return file_ctap_ctap_proto_rawDescGZIP(), []int{1}
}

func (x *CtapResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_ctap_ctap_proto protoreflect.FileDescriptor

const file_ctap_ctap_proto_rawDesc = "" +
	"\n" +
	"\x0fctap/ctap.proto\x12\x04ctap\"M\n" +
	"\vCtapRequest\x12\x10\n" +
	"\x03Req\x18\x01 \x01(\tR\x03Req\x12\x12\n" +
	"\x04Args\x18\x02 \x03(\tR\x04Args\x12\x18\n" +
	"\aPayload\x18\x03 \x01(\fR\aPayload\"&\n" +
	"\fCtapResponse\x12\x16\n" +
	"\x06Output\x18\x01 \x01(\fR\x06Output27\n" +
	"\x04Ctap\x12/\n" +
	"\x04Ctap\x12\x11.ctap.CtapRequest\x1a\x12.ctap.CtapResponse\"\x00B\bZ\x06./ctapb\x06proto3"

var (
	file_ctap_ctap_proto_rawDescOnce sync.Once
	file_ctap_ctap_proto_rawDescData []byte
)

func file_ctap_ctap_proto_rawDescGZIP() []byte {
	file_ctap_ctap_proto_rawDescOnce.Do(func() {
		file_ctap_ctap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctap_ctap_proto_rawDesc), len(file_ctap_ctap_proto_rawDesc)))
	})
	return file_ctap_ctap_proto_rawDescData
}

var file_ctap_ctap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ctap_ctap_proto_goTypes = []any{
	(*CtapRequest)(nil),  // 0: ctap.CtapRequest
	(*CtapResponse)(nil), // 1: ctap.CtapResponse
}
var file_ctap_ctap_proto_depIdxs = []int32{
	0, // 0: ctap.Ctap.Ctap:input_type -> ctap.CtapRequest
	1, // 1: ctap.Ctap.Ctap:output_type -> ctap.CtapResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ctap_ctap_proto_init() }
func file_ctap_ctap_proto_init() {
	if File_ctap_ctap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctap_ctap_proto_rawDesc), len(file_ctap_ctap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ctap_ctap_proto_goTypes,
		DependencyIndexes: file_ctap_ctap_proto_depIdxs,
		MessageInfos:      file_ctap_ctap_proto_msgTypes,
	}.Build()
	File_ctap_ctap_proto = out.File
	file_ctap_ctap_proto_goTypes = nil
	file_ctap_ctap_proto_depIdxs = nil
}
