# Copyright 2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0
[devshell]
name = "givc-devshell"

packages = [
    "go",
    "gotests",
    "gopls",
    "golangci-lint",
    "rustc",
    "rustfmt",
    "cargo",
    "protobuf",
    "protoc-gen-go",
    "protoc-gen-go-grpc",
    "grpcurl",
    "pkgs.stdenv.cc"
]

[[commands]]
help = "Generate go files from protobuffers"
name = "protogen"
command = "./api/protoc.sh"

[[commands]]
help = "Like cURL, but for gRPC: Command-line tool for interacting with gRPC servers"
name = "gcl"
command = "grpcurl"

[[commands]]
help = "Update go dependencies"
name = "go-update"
command = "go get -u ./... && go mod tidy && echo Done - do not forget to update the vendorHash in the packages."

[[commands]]
help = "golang linter"
package = "golangci-lint"
category = "linters"