// Socket Proxy Service API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: socket/socket.proto

package socketproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stream frame with raw bytes and explicit EOF signalling.
// `chunk` is always the payload bytes for this frame.
// EOF is represented by `eof = true` (typically with empty `chunk`).
type StreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw payload bytes.
	Chunk []byte `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	// true when this frame marks end of stream.
	Eof           bool `protobuf:"varint,2,opt,name=Eof,proto3" json:"Eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_socket_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_socket_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_socket_socket_proto_rawDescGZIP(), []int{0}
}

func (x *StreamFrame) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *StreamFrame) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_socket_socket_proto protoreflect.FileDescriptor

const file_socket_socket_proto_rawDesc = "" +
	"\n" +
	"\x13socket/socket.proto\x12\vsocketproxy\"5\n" +
	"\vStreamFrame\x12\x14\n" +
	"\x05Chunk\x18\x01 \x01(\fR\x05Chunk\x12\x10\n" +
	"\x03Eof\x18\x02 \x01(\bR\x03Eof2X\n" +
	"\fSocketStream\x12H\n" +
	"\fTransferData\x12\x18.socketproxy.StreamFrame\x1a\x18.socketproxy.StreamFrame\"\x00(\x010\x01B\x1eZ\x1cgivc/modules/api/socketproxyb\x06proto3"

var (
	file_socket_socket_proto_rawDescOnce sync.Once
	file_socket_socket_proto_rawDescData []byte
)

func file_socket_socket_proto_rawDescGZIP() []byte {
	file_socket_socket_proto_rawDescOnce.Do(func() {
		file_socket_socket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socket_socket_proto_rawDesc), len(file_socket_socket_proto_rawDesc)))
	})
	return file_socket_socket_proto_rawDescData
}

var file_socket_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socket_socket_proto_goTypes = []any{
	(*StreamFrame)(nil), // 0: socketproxy.StreamFrame
}
var file_socket_socket_proto_depIdxs = []int32{
	0, // 0: socketproxy.SocketStream.TransferData:input_type -> socketproxy.StreamFrame
	0, // 1: socketproxy.SocketStream.TransferData:output_type -> socketproxy.StreamFrame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socket_socket_proto_init() }
func file_socket_socket_proto_init() {
	if File_socket_socket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_socket_proto_rawDesc), len(file_socket_socket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_socket_socket_proto_goTypes,
		DependencyIndexes: file_socket_socket_proto_depIdxs,
		MessageInfos:      file_socket_socket_proto_msgTypes,
	}.Build()
	File_socket_socket_proto = out.File
	file_socket_socket_proto_goTypes = nil
	file_socket_socket_proto_depIdxs = nil
}
