// Copyright 2024 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: socket/socket.proto

package socketproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BytePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytePacket) Reset() {
	*x = BytePacket{}
	mi := &file_socket_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytePacket) ProtoMessage() {}

func (x *BytePacket) ProtoReflect() protoreflect.Message {
	mi := &file_socket_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytePacket.ProtoReflect.Descriptor instead.
func (*BytePacket) Descriptor() ([]byte, []int) {
	return file_socket_socket_proto_rawDescGZIP(), []int{0}
}

func (x *BytePacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_socket_socket_proto protoreflect.FileDescriptor

const file_socket_socket_proto_rawDesc = "" +
	"\n" +
	"\x13socket/socket.proto\x12\vsocketproxy\" \n" +
	"\n" +
	"BytePacket\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data2V\n" +
	"\fSocketStream\x12F\n" +
	"\fTransferData\x12\x17.socketproxy.BytePacket\x1a\x17.socketproxy.BytePacket\"\x00(\x010\x01B\x1eZ\x1cgivc/modules/api/socketproxyb\x06proto3"

var (
	file_socket_socket_proto_rawDescOnce sync.Once
	file_socket_socket_proto_rawDescData []byte
)

func file_socket_socket_proto_rawDescGZIP() []byte {
	file_socket_socket_proto_rawDescOnce.Do(func() {
		file_socket_socket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socket_socket_proto_rawDesc), len(file_socket_socket_proto_rawDesc)))
	})
	return file_socket_socket_proto_rawDescData
}

var file_socket_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socket_socket_proto_goTypes = []any{
	(*BytePacket)(nil), // 0: socketproxy.BytePacket
}
var file_socket_socket_proto_depIdxs = []int32{
	0, // 0: socketproxy.SocketStream.TransferData:input_type -> socketproxy.BytePacket
	0, // 1: socketproxy.SocketStream.TransferData:output_type -> socketproxy.BytePacket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socket_socket_proto_init() }
func file_socket_socket_proto_init() {
	if File_socket_socket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_socket_proto_rawDesc), len(file_socket_socket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_socket_socket_proto_goTypes,
		DependencyIndexes: file_socket_socket_proto_depIdxs,
		MessageInfos:      file_socket_socket_proto_msgTypes,
	}.Build()
	File_socket_socket_proto = out.File
	file_socket_socket_proto_goTypes = nil
	file_socket_socket_proto_depIdxs = nil
}
