// Stats Service API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: vm/vm.proto

package vm

import (
	stats "givc/modules/api/stats"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty stats request message
type VMStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStatsRequest) Reset() {
	*x = VMStatsRequest{}
	mi := &file_vm_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStatsRequest) ProtoMessage() {}

func (x *VMStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vm_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStatsRequest.ProtoReflect.Descriptor instead.
func (*VMStatsRequest) Descriptor() ([]byte, []int) {
	return file_vm_vm_proto_rawDescGZIP(), []int{0}
}

func (x *VMStatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VMSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            string                 `protobuf:"bytes,1,opt,name=Vm,proto3" json:"Vm,omitempty"`
	Minimum       *uint64                `protobuf:"varint,2,opt,name=Minimum,proto3,oneof" json:"Minimum,omitempty"`
	Maximum       *uint64                `protobuf:"varint,3,opt,name=Maximum,proto3,oneof" json:"Maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMSizeRequest) Reset() {
	*x = VMSizeRequest{}
	mi := &file_vm_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSizeRequest) ProtoMessage() {}

func (x *VMSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vm_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSizeRequest.ProtoReflect.Descriptor instead.
func (*VMSizeRequest) Descriptor() ([]byte, []int) {
	return file_vm_vm_proto_rawDescGZIP(), []int{1}
}

func (x *VMSizeRequest) GetVm() string {
	if x != nil {
		return x.Vm
	}
	return ""
}

func (x *VMSizeRequest) GetMinimum() uint64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *VMSizeRequest) GetMaximum() uint64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

type VMSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minimum       uint64                 `protobuf:"varint,1,opt,name=Minimum,proto3" json:"Minimum,omitempty"`
	Maximum       uint64                 `protobuf:"varint,2,opt,name=Maximum,proto3" json:"Maximum,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMSizeResponse) Reset() {
	*x = VMSizeResponse{}
	mi := &file_vm_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSizeResponse) ProtoMessage() {}

func (x *VMSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vm_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSizeResponse.ProtoReflect.Descriptor instead.
func (*VMSizeResponse) Descriptor() ([]byte, []int) {
	return file_vm_vm_proto_rawDescGZIP(), []int{2}
}

func (x *VMSizeResponse) GetMinimum() uint64 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *VMSizeResponse) GetMaximum() uint64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *VMSizeResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_vm_vm_proto protoreflect.FileDescriptor

const file_vm_vm_proto_rawDesc = "" +
	"\n" +
	"\vvm/vm.proto\x12\x02vm\x1a\x11stats/stats.proto\"$\n" +
	"\x0eVMStatsRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"u\n" +
	"\rVMSizeRequest\x12\x0e\n" +
	"\x02Vm\x18\x01 \x01(\tR\x02Vm\x12\x1d\n" +
	"\aMinimum\x18\x02 \x01(\x04H\x00R\aMinimum\x88\x01\x01\x12\x1d\n" +
	"\aMaximum\x18\x03 \x01(\x04H\x01R\aMaximum\x88\x01\x01B\n" +
	"\n" +
	"\b_MinimumB\n" +
	"\n" +
	"\b_Maximum\"X\n" +
	"\x0eVMSizeResponse\x12\x18\n" +
	"\aMinimum\x18\x01 \x01(\x04R\aMinimum\x12\x18\n" +
	"\aMaximum\x18\x02 \x01(\x04R\aMaximum\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\x04R\x04Size2w\n" +
	"\tVMService\x124\n" +
	"\bGetStats\x12\x12.vm.VMStatsRequest\x1a\x12.stats.MemoryStats\"\x00\x124\n" +
	"\tSetVMSize\x12\x11.vm.VMSizeRequest\x1a\x12.vm.VMSizeResponse\"\x00B\x15Z\x13givc/modules/api/vmb\x06proto3"

var (
	file_vm_vm_proto_rawDescOnce sync.Once
	file_vm_vm_proto_rawDescData []byte
)

func file_vm_vm_proto_rawDescGZIP() []byte {
	file_vm_vm_proto_rawDescOnce.Do(func() {
		file_vm_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_vm_proto_rawDesc), len(file_vm_vm_proto_rawDesc)))
	})
	return file_vm_vm_proto_rawDescData
}

var file_vm_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vm_vm_proto_goTypes = []any{
	(*VMStatsRequest)(nil),    // 0: vm.VMStatsRequest
	(*VMSizeRequest)(nil),     // 1: vm.VMSizeRequest
	(*VMSizeResponse)(nil),    // 2: vm.VMSizeResponse
	(*stats.MemoryStats)(nil), // 3: stats.MemoryStats
}
var file_vm_vm_proto_depIdxs = []int32{
	0, // 0: vm.VMService.GetStats:input_type -> vm.VMStatsRequest
	1, // 1: vm.VMService.SetVMSize:input_type -> vm.VMSizeRequest
	3, // 2: vm.VMService.GetStats:output_type -> stats.MemoryStats
	2, // 3: vm.VMService.SetVMSize:output_type -> vm.VMSizeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vm_vm_proto_init() }
func file_vm_vm_proto_init() {
	if File_vm_vm_proto != nil {
		return
	}
	file_vm_vm_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_vm_proto_rawDesc), len(file_vm_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vm_vm_proto_goTypes,
		DependencyIndexes: file_vm_vm_proto_depIdxs,
		MessageInfos:      file_vm_vm_proto_msgTypes,
	}.Build()
	File_vm_vm_proto = out.File
	file_vm_vm_proto_goTypes = nil
	file_vm_vm_proto_depIdxs = nil
}
