// SPDX-FileCopyrightText: 2025-2026 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: policyadmin/policyadmin.proto

package policyadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyAdmin_StreamPolicy_FullMethodName = "/policyadmin.PolicyAdmin/StreamPolicy"
)

// PolicyAdminClient is the client API for PolicyAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyAdminClient interface {
	StreamPolicy(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamPolicyRequest, Status], error)
}

type policyAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyAdminClient(cc grpc.ClientConnInterface) PolicyAdminClient {
	return &policyAdminClient{cc}
}

func (c *policyAdminClient) StreamPolicy(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamPolicyRequest, Status], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyAdmin_ServiceDesc.Streams[0], PolicyAdmin_StreamPolicy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPolicyRequest, Status]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyAdmin_StreamPolicyClient = grpc.ClientStreamingClient[StreamPolicyRequest, Status]

// PolicyAdminServer is the server API for PolicyAdmin service.
// All implementations must embed UnimplementedPolicyAdminServer
// for forward compatibility.
type PolicyAdminServer interface {
	StreamPolicy(grpc.ClientStreamingServer[StreamPolicyRequest, Status]) error
	mustEmbedUnimplementedPolicyAdminServer()
}

// UnimplementedPolicyAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyAdminServer struct{}

func (UnimplementedPolicyAdminServer) StreamPolicy(grpc.ClientStreamingServer[StreamPolicyRequest, Status]) error {
	return status.Error(codes.Unimplemented, "method StreamPolicy not implemented")
}
func (UnimplementedPolicyAdminServer) mustEmbedUnimplementedPolicyAdminServer() {}
func (UnimplementedPolicyAdminServer) testEmbeddedByValue()                     {}

// UnsafePolicyAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyAdminServer will
// result in compilation errors.
type UnsafePolicyAdminServer interface {
	mustEmbedUnimplementedPolicyAdminServer()
}

func RegisterPolicyAdminServer(s grpc.ServiceRegistrar, srv PolicyAdminServer) {
	// If the following call panics, it indicates UnimplementedPolicyAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyAdmin_ServiceDesc, srv)
}

func _PolicyAdmin_StreamPolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyAdminServer).StreamPolicy(&grpc.GenericServerStream[StreamPolicyRequest, Status]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyAdmin_StreamPolicyServer = grpc.ClientStreamingServer[StreamPolicyRequest, Status]

// PolicyAdmin_ServiceDesc is the grpc.ServiceDesc for PolicyAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policyadmin.PolicyAdmin",
	HandlerType: (*PolicyAdminServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPolicy",
			Handler:       _PolicyAdmin_StreamPolicy_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "policyadmin/policyadmin.proto",
}
