// Update Service API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: update/update.proto

package update

import (
	admin "givc/modules/api/admin"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_update_update_proto protoreflect.FileDescriptor

const file_update_update_proto_rawDesc = "" +
	"\n" +
	"\x13update/update.proto\x12\x06update\x1a\x11admin/admin.proto2\xc0\x03\n" +
	"\x06Update\x12A\n" +
	"\x0fListGenerations\x12\f.admin.Empty\x1a\x1e.admin.ListGenerationsResponse\"\x00\x12M\n" +
	"\bDiscover\x12\x1e.admin.RegistryDiscoverRequest\x1a\x1f.admin.RegistryDiscoverResponse\"\x00\x12P\n" +
	"\tChangelog\x12\x1f.admin.RegistryChangelogRequest\x1a .admin.RegistryChangelogResponse\"\x00\x12C\n" +
	"\x04Pull\x12\x1a.admin.RegistryPullRequest\x1a\x1b.admin.RegistryPullResponse\"\x000\x01\x12K\n" +
	"\fImageInstall\x12\x1a.admin.ImageInstallRequest\x1a\x1b.admin.ImageInstallResponse\"\x000\x01\x12@\n" +
	"\rInstallCachix\x12\r.admin.Cachix\x1a\x1c.admin.SetGenerationResponse\"\x000\x01B\x19Z\x17givc/modules/api/updateb\x06proto3"

var file_update_update_proto_goTypes = []any{
	(*admin.Empty)(nil),                     // 0: admin.Empty
	(*admin.RegistryDiscoverRequest)(nil),   // 1: admin.RegistryDiscoverRequest
	(*admin.RegistryChangelogRequest)(nil),  // 2: admin.RegistryChangelogRequest
	(*admin.RegistryPullRequest)(nil),       // 3: admin.RegistryPullRequest
	(*admin.ImageInstallRequest)(nil),       // 4: admin.ImageInstallRequest
	(*admin.Cachix)(nil),                    // 5: admin.Cachix
	(*admin.ListGenerationsResponse)(nil),   // 6: admin.ListGenerationsResponse
	(*admin.RegistryDiscoverResponse)(nil),  // 7: admin.RegistryDiscoverResponse
	(*admin.RegistryChangelogResponse)(nil), // 8: admin.RegistryChangelogResponse
	(*admin.RegistryPullResponse)(nil),      // 9: admin.RegistryPullResponse
	(*admin.ImageInstallResponse)(nil),      // 10: admin.ImageInstallResponse
	(*admin.SetGenerationResponse)(nil),     // 11: admin.SetGenerationResponse
}
var file_update_update_proto_depIdxs = []int32{
	0,  // 0: update.Update.ListGenerations:input_type -> admin.Empty
	1,  // 1: update.Update.Discover:input_type -> admin.RegistryDiscoverRequest
	2,  // 2: update.Update.Changelog:input_type -> admin.RegistryChangelogRequest
	3,  // 3: update.Update.Pull:input_type -> admin.RegistryPullRequest
	4,  // 4: update.Update.ImageInstall:input_type -> admin.ImageInstallRequest
	5,  // 5: update.Update.InstallCachix:input_type -> admin.Cachix
	6,  // 6: update.Update.ListGenerations:output_type -> admin.ListGenerationsResponse
	7,  // 7: update.Update.Discover:output_type -> admin.RegistryDiscoverResponse
	8,  // 8: update.Update.Changelog:output_type -> admin.RegistryChangelogResponse
	9,  // 9: update.Update.Pull:output_type -> admin.RegistryPullResponse
	10, // 10: update.Update.ImageInstall:output_type -> admin.ImageInstallResponse
	11, // 11: update.Update.InstallCachix:output_type -> admin.SetGenerationResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_update_update_proto_init() }
func file_update_update_proto_init() {
	if File_update_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_update_proto_rawDesc), len(file_update_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_update_update_proto_goTypes,
		DependencyIndexes: file_update_update_proto_depIdxs,
	}.Build()
	File_update_update_proto = out.File
	file_update_update_proto_goTypes = nil
	file_update_update_proto_depIdxs = nil
}
