// Update Service API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: update/update.proto

package update

import (
	context "context"
	admin "givc/modules/api/admin"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Update_ListGenerations_FullMethodName = "/update.Update/ListGenerations"
	Update_Discover_FullMethodName        = "/update.Update/Discover"
	Update_Changelog_FullMethodName       = "/update.Update/Changelog"
	Update_Pull_FullMethodName            = "/update.Update/Pull"
	Update_ImageInstall_FullMethodName    = "/update.Update/ImageInstall"
	Update_InstallCachix_FullMethodName   = "/update.Update/InstallCachix"
)

// UpdateClient is the client API for Update service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateClient interface {
	// List installed generations (updates)
	ListGenerations(ctx context.Context, in *admin.Empty, opts ...grpc.CallOption) (*admin.ListGenerationsResponse, error)
	// Discover available OTA updates in an OCI repository
	Discover(ctx context.Context, in *admin.RegistryDiscoverRequest, opts ...grpc.CallOption) (*admin.RegistryDiscoverResponse, error)
	// Fetch changelog text for a specific registry tag
	Changelog(ctx context.Context, in *admin.RegistryChangelogRequest, opts ...grpc.CallOption) (*admin.RegistryChangelogResponse, error)
	// Pull OTA update artifacts from an OCI repository
	Pull(ctx context.Context, in *admin.RegistryPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.RegistryPullResponse], error)
	// Install image on ghaf-host from a manifest path
	ImageInstall(ctx context.Context, in *admin.ImageInstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.ImageInstallResponse], error)
	// Install a pinned release from Cachix
	InstallCachix(ctx context.Context, in *admin.Cachix, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.SetGenerationResponse], error)
}

type updateClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateClient(cc grpc.ClientConnInterface) UpdateClient {
	return &updateClient{cc}
}

func (c *updateClient) ListGenerations(ctx context.Context, in *admin.Empty, opts ...grpc.CallOption) (*admin.ListGenerationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(admin.ListGenerationsResponse)
	err := c.cc.Invoke(ctx, Update_ListGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) Discover(ctx context.Context, in *admin.RegistryDiscoverRequest, opts ...grpc.CallOption) (*admin.RegistryDiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(admin.RegistryDiscoverResponse)
	err := c.cc.Invoke(ctx, Update_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) Changelog(ctx context.Context, in *admin.RegistryChangelogRequest, opts ...grpc.CallOption) (*admin.RegistryChangelogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(admin.RegistryChangelogResponse)
	err := c.cc.Invoke(ctx, Update_Changelog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) Pull(ctx context.Context, in *admin.RegistryPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.RegistryPullResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Update_ServiceDesc.Streams[0], Update_Pull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[admin.RegistryPullRequest, admin.RegistryPullResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_PullClient = grpc.ServerStreamingClient[admin.RegistryPullResponse]

func (c *updateClient) ImageInstall(ctx context.Context, in *admin.ImageInstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.ImageInstallResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Update_ServiceDesc.Streams[1], Update_ImageInstall_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[admin.ImageInstallRequest, admin.ImageInstallResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_ImageInstallClient = grpc.ServerStreamingClient[admin.ImageInstallResponse]

func (c *updateClient) InstallCachix(ctx context.Context, in *admin.Cachix, opts ...grpc.CallOption) (grpc.ServerStreamingClient[admin.SetGenerationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Update_ServiceDesc.Streams[2], Update_InstallCachix_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[admin.Cachix, admin.SetGenerationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_InstallCachixClient = grpc.ServerStreamingClient[admin.SetGenerationResponse]

// UpdateServer is the server API for Update service.
// All implementations must embed UnimplementedUpdateServer
// for forward compatibility.
type UpdateServer interface {
	// List installed generations (updates)
	ListGenerations(context.Context, *admin.Empty) (*admin.ListGenerationsResponse, error)
	// Discover available OTA updates in an OCI repository
	Discover(context.Context, *admin.RegistryDiscoverRequest) (*admin.RegistryDiscoverResponse, error)
	// Fetch changelog text for a specific registry tag
	Changelog(context.Context, *admin.RegistryChangelogRequest) (*admin.RegistryChangelogResponse, error)
	// Pull OTA update artifacts from an OCI repository
	Pull(*admin.RegistryPullRequest, grpc.ServerStreamingServer[admin.RegistryPullResponse]) error
	// Install image on ghaf-host from a manifest path
	ImageInstall(*admin.ImageInstallRequest, grpc.ServerStreamingServer[admin.ImageInstallResponse]) error
	// Install a pinned release from Cachix
	InstallCachix(*admin.Cachix, grpc.ServerStreamingServer[admin.SetGenerationResponse]) error
	mustEmbedUnimplementedUpdateServer()
}

// UnimplementedUpdateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateServer struct{}

func (UnimplementedUpdateServer) ListGenerations(context.Context, *admin.Empty) (*admin.ListGenerationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGenerations not implemented")
}
func (UnimplementedUpdateServer) Discover(context.Context, *admin.RegistryDiscoverRequest) (*admin.RegistryDiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedUpdateServer) Changelog(context.Context, *admin.RegistryChangelogRequest) (*admin.RegistryChangelogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Changelog not implemented")
}
func (UnimplementedUpdateServer) Pull(*admin.RegistryPullRequest, grpc.ServerStreamingServer[admin.RegistryPullResponse]) error {
	return status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedUpdateServer) ImageInstall(*admin.ImageInstallRequest, grpc.ServerStreamingServer[admin.ImageInstallResponse]) error {
	return status.Error(codes.Unimplemented, "method ImageInstall not implemented")
}
func (UnimplementedUpdateServer) InstallCachix(*admin.Cachix, grpc.ServerStreamingServer[admin.SetGenerationResponse]) error {
	return status.Error(codes.Unimplemented, "method InstallCachix not implemented")
}
func (UnimplementedUpdateServer) mustEmbedUnimplementedUpdateServer() {}
func (UnimplementedUpdateServer) testEmbeddedByValue()                {}

// UnsafeUpdateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateServer will
// result in compilation errors.
type UnsafeUpdateServer interface {
	mustEmbedUnimplementedUpdateServer()
}

func RegisterUpdateServer(s grpc.ServiceRegistrar, srv UpdateServer) {
	// If the following call panics, it indicates UnimplementedUpdateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Update_ServiceDesc, srv)
}

func _Update_ListGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(admin.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).ListGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_ListGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).ListGenerations(ctx, req.(*admin.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(admin.RegistryDiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Discover(ctx, req.(*admin.RegistryDiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_Changelog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(admin.RegistryChangelogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Changelog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Update_Changelog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Changelog(ctx, req.(*admin.RegistryChangelogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(admin.RegistryPullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateServer).Pull(m, &grpc.GenericServerStream[admin.RegistryPullRequest, admin.RegistryPullResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_PullServer = grpc.ServerStreamingServer[admin.RegistryPullResponse]

func _Update_ImageInstall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(admin.ImageInstallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateServer).ImageInstall(m, &grpc.GenericServerStream[admin.ImageInstallRequest, admin.ImageInstallResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_ImageInstallServer = grpc.ServerStreamingServer[admin.ImageInstallResponse]

func _Update_InstallCachix_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(admin.Cachix)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateServer).InstallCachix(m, &grpc.GenericServerStream[admin.Cachix, admin.SetGenerationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Update_InstallCachixServer = grpc.ServerStreamingServer[admin.SetGenerationResponse]

// Update_ServiceDesc is the grpc.ServiceDesc for Update service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Update_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "update.Update",
	HandlerType: (*UpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGenerations",
			Handler:    _Update_ListGenerations_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Update_Discover_Handler,
		},
		{
			MethodName: "Changelog",
			Handler:    _Update_Changelog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _Update_Pull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImageInstall",
			Handler:       _Update_ImageInstall_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallCachix",
			Handler:       _Update_InstallCachix_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "update/update.proto",
}
