// Update Service API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: update/update.proto

package update

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_update_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{0}
}

type Generation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Generation            int32                  `protobuf:"varint,1,opt,name=Generation,proto3" json:"Generation,omitempty"`                      // Numeric generation identifier
	Date                  string                 `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`                                   // Build or activation date
	NixosVersion          string                 `protobuf:"bytes,3,opt,name=NixosVersion,proto3" json:"NixosVersion,omitempty"`                   // NixOS release version
	KernelVersion         string                 `protobuf:"bytes,4,opt,name=KernelVersion,proto3" json:"KernelVersion,omitempty"`                 // Kernel version string
	ConfigurationRevision string                 `protobuf:"bytes,5,opt,name=ConfigurationRevision,proto3" json:"ConfigurationRevision,omitempty"` // Configuration revision hash
	Specialisations       []string               `protobuf:"bytes,6,rep,name=Specialisations,proto3" json:"Specialisations,omitempty"`             // Enabled specialisations
	Current               bool                   `protobuf:"varint,7,opt,name=Current,proto3" json:"Current,omitempty"`                            // True if this is the active generation
	StorePath             string                 `protobuf:"bytes,8,opt,name=StorePath,proto3" json:"StorePath,omitempty"`                         // Nix store path for the generation
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_update_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{1}
}

func (x *Generation) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Generation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Generation) GetNixosVersion() string {
	if x != nil {
		return x.NixosVersion
	}
	return ""
}

func (x *Generation) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *Generation) GetConfigurationRevision() string {
	if x != nil {
		return x.ConfigurationRevision
	}
	return ""
}

func (x *Generation) GetSpecialisations() []string {
	if x != nil {
		return x.Specialisations
	}
	return nil
}

func (x *Generation) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *Generation) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

type ListGenerationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Generation          `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // List of installed generations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenerationsResponse) Reset() {
	*x = ListGenerationsResponse{}
	mi := &file_update_update_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenerationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenerationsResponse) ProtoMessage() {}

func (x *ListGenerationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenerationsResponse.ProtoReflect.Descriptor instead.
func (*ListGenerationsResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{2}
}

func (x *ListGenerationsResponse) GetList() []*Generation {
	if x != nil {
		return x.List
	}
	return nil
}

type SetGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*SetGenerationRequest_Cachix
	Update        isSetGenerationRequest_Update `protobuf_oneof:"Update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGenerationRequest) Reset() {
	*x = SetGenerationRequest{}
	mi := &file_update_update_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGenerationRequest) ProtoMessage() {}

func (x *SetGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGenerationRequest.ProtoReflect.Descriptor instead.
func (*SetGenerationRequest) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{3}
}

func (x *SetGenerationRequest) GetUpdate() isSetGenerationRequest_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SetGenerationRequest) GetCachix() *Cachix {
	if x != nil {
		if x, ok := x.Update.(*SetGenerationRequest_Cachix); ok {
			return x.Cachix
		}
	}
	return nil
}

type isSetGenerationRequest_Update interface {
	isSetGenerationRequest_Update()
}

type SetGenerationRequest_Cachix struct {
	Cachix *Cachix `protobuf:"bytes,1,opt,name=Cachix,proto3,oneof"` // Cachix-based update payload
}

func (*SetGenerationRequest_Cachix) isSetGenerationRequest_Update() {}

type Cachix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=Pin,proto3" json:"Pin,omitempty"`                     // Pinned release name
	CachixHost    *string                `protobuf:"bytes,2,opt,name=CachixHost,proto3,oneof" json:"CachixHost,omitempty"` // API url for cachix
	Cache         string                 `protobuf:"bytes,3,opt,name=Cache,proto3" json:"Cache,omitempty"`                 // Cachix cache name
	Token         *string                `protobuf:"bytes,4,opt,name=Token,proto3,oneof" json:"Token,omitempty"`           // Optional API token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cachix) Reset() {
	*x = Cachix{}
	mi := &file_update_update_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cachix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cachix) ProtoMessage() {}

func (x *Cachix) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cachix.ProtoReflect.Descriptor instead.
func (*Cachix) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{4}
}

func (x *Cachix) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Cachix) GetCachixHost() string {
	if x != nil && x.CachixHost != nil {
		return *x.CachixHost
	}
	return ""
}

func (x *Cachix) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *Cachix) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type SetGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      bool                   `protobuf:"varint,1,opt,name=Finished,proto3" json:"Finished,omitempty"`  // True when the command completed
	Output        *string                `protobuf:"bytes,2,opt,name=Output,proto3,oneof" json:"Output,omitempty"` // Standard output from the command
	Error         *string                `protobuf:"bytes,3,opt,name=Error,proto3,oneof" json:"Error,omitempty"`   // Standard error from the command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGenerationResponse) Reset() {
	*x = SetGenerationResponse{}
	mi := &file_update_update_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGenerationResponse) ProtoMessage() {}

func (x *SetGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGenerationResponse.ProtoReflect.Descriptor instead.
func (*SetGenerationResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{5}
}

func (x *SetGenerationResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *SetGenerationResponse) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *SetGenerationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type RegistryBasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"` // Registry username
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"` // Registry password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryBasicAuth) Reset() {
	*x = RegistryBasicAuth{}
	mi := &file_update_update_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryBasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryBasicAuth) ProtoMessage() {}

func (x *RegistryBasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryBasicAuth.ProtoReflect.Descriptor instead.
func (*RegistryBasicAuth) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryBasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryBasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistryBearerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // Registry bearer token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryBearerAuth) Reset() {
	*x = RegistryBearerAuth{}
	mi := &file_update_update_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryBearerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryBearerAuth) ProtoMessage() {}

func (x *RegistryBearerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryBearerAuth.ProtoReflect.Descriptor instead.
func (*RegistryBearerAuth) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{7}
}

func (x *RegistryBearerAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegistryCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Auth:
	//
	//	*RegistryCredentials_Basic
	//	*RegistryCredentials_Bearer
	Auth          isRegistryCredentials_Auth `protobuf_oneof:"Auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentials) Reset() {
	*x = RegistryCredentials{}
	mi := &file_update_update_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentials) ProtoMessage() {}

func (x *RegistryCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentials.ProtoReflect.Descriptor instead.
func (*RegistryCredentials) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{8}
}

func (x *RegistryCredentials) GetAuth() isRegistryCredentials_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *RegistryCredentials) GetBasic() *RegistryBasicAuth {
	if x != nil {
		if x, ok := x.Auth.(*RegistryCredentials_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *RegistryCredentials) GetBearer() *RegistryBearerAuth {
	if x != nil {
		if x, ok := x.Auth.(*RegistryCredentials_Bearer); ok {
			return x.Bearer
		}
	}
	return nil
}

type isRegistryCredentials_Auth interface {
	isRegistryCredentials_Auth()
}

type RegistryCredentials_Basic struct {
	Basic *RegistryBasicAuth `protobuf:"bytes,1,opt,name=Basic,proto3,oneof"` // Basic auth credentials
}

type RegistryCredentials_Bearer struct {
	Bearer *RegistryBearerAuth `protobuf:"bytes,2,opt,name=Bearer,proto3,oneof"` // Bearer auth credentials
}

func (*RegistryCredentials_Basic) isRegistryCredentials_Auth() {}

func (*RegistryCredentials_Bearer) isRegistryCredentials_Auth() {}

type AvailableUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=Repository,proto3" json:"Repository,omitempty"` // OCI repository name
	Tag           string                 `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`               // Update tag
	Version       string                 `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`       // Update version
	Hash          string                 `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`             // Artifact hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableUpdate) Reset() {
	*x = AvailableUpdate{}
	mi := &file_update_update_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableUpdate) ProtoMessage() {}

func (x *AvailableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableUpdate.ProtoReflect.Descriptor instead.
func (*AvailableUpdate) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{9}
}

func (x *AvailableUpdate) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *AvailableUpdate) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AvailableUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AvailableUpdate) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RegistryDiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`           // OCI reference to search
	Insecure      bool                   `protobuf:"varint,2,opt,name=Insecure,proto3" json:"Insecure,omitempty"`            // Use HTTP instead of HTTPS
	Credentials   *RegistryCredentials   `protobuf:"bytes,3,opt,name=Credentials,proto3,oneof" json:"Credentials,omitempty"` // Optional registry credentials
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryDiscoverRequest) Reset() {
	*x = RegistryDiscoverRequest{}
	mi := &file_update_update_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryDiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryDiscoverRequest) ProtoMessage() {}

func (x *RegistryDiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryDiscoverRequest.ProtoReflect.Descriptor instead.
func (*RegistryDiscoverRequest) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{10}
}

func (x *RegistryDiscoverRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RegistryDiscoverRequest) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *RegistryDiscoverRequest) GetCredentials() *RegistryCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RegistryDiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AvailableUpdate     `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // Matching update entries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryDiscoverResponse) Reset() {
	*x = RegistryDiscoverResponse{}
	mi := &file_update_update_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryDiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryDiscoverResponse) ProtoMessage() {}

func (x *RegistryDiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryDiscoverResponse.ProtoReflect.Descriptor instead.
func (*RegistryDiscoverResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{11}
}

func (x *RegistryDiscoverResponse) GetList() []*AvailableUpdate {
	if x != nil {
		return x.List
	}
	return nil
}

type RegistryChangelogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`           // OCI reference to inspect
	Insecure      bool                   `protobuf:"varint,2,opt,name=Insecure,proto3" json:"Insecure,omitempty"`            // Use HTTP instead of HTTPS
	Credentials   *RegistryCredentials   `protobuf:"bytes,3,opt,name=Credentials,proto3,oneof" json:"Credentials,omitempty"` // Optional registry credentials
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryChangelogRequest) Reset() {
	*x = RegistryChangelogRequest{}
	mi := &file_update_update_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryChangelogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryChangelogRequest) ProtoMessage() {}

func (x *RegistryChangelogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryChangelogRequest.ProtoReflect.Descriptor instead.
func (*RegistryChangelogRequest) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryChangelogRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RegistryChangelogRequest) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *RegistryChangelogRequest) GetCredentials() *RegistryCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RegistryChangelogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changelog     string                 `protobuf:"bytes,1,opt,name=Changelog,proto3" json:"Changelog,omitempty"` // Changelog text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryChangelogResponse) Reset() {
	*x = RegistryChangelogResponse{}
	mi := &file_update_update_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryChangelogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryChangelogResponse) ProtoMessage() {}

func (x *RegistryChangelogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryChangelogResponse.ProtoReflect.Descriptor instead.
func (*RegistryChangelogResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{13}
}

func (x *RegistryChangelogResponse) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

type RegistryPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`           // OCI tag reference to pull
	Destination   string                 `protobuf:"bytes,2,opt,name=Destination,proto3" json:"Destination,omitempty"`       // Destination directory
	Insecure      bool                   `protobuf:"varint,4,opt,name=Insecure,proto3" json:"Insecure,omitempty"`            // Use HTTP instead of HTTPS
	Credentials   *RegistryCredentials   `protobuf:"bytes,5,opt,name=Credentials,proto3,oneof" json:"Credentials,omitempty"` // Optional registry credentials
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPullRequest) Reset() {
	*x = RegistryPullRequest{}
	mi := &file_update_update_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPullRequest) ProtoMessage() {}

func (x *RegistryPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPullRequest.ProtoReflect.Descriptor instead.
func (*RegistryPullRequest) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{14}
}

func (x *RegistryPullRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RegistryPullRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RegistryPullRequest) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *RegistryPullRequest) GetCredentials() *RegistryCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RegistryPullResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputDir     string                 `protobuf:"bytes,1,opt,name=OutputDir,proto3" json:"OutputDir,omitempty"`       // Output directory
	ManifestPath  string                 `protobuf:"bytes,2,opt,name=ManifestPath,proto3" json:"ManifestPath,omitempty"` // Written manifest path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPullResult) Reset() {
	*x = RegistryPullResult{}
	mi := &file_update_update_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPullResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPullResult) ProtoMessage() {}

func (x *RegistryPullResult) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPullResult.ProtoReflect.Descriptor instead.
func (*RegistryPullResult) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{15}
}

func (x *RegistryPullResult) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *RegistryPullResult) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

type RegistryPullStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`     // OCI reference being pulled
	Destination   string                 `protobuf:"bytes,2,opt,name=Destination,proto3" json:"Destination,omitempty"` // Destination directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPullStarted) Reset() {
	*x = RegistryPullStarted{}
	mi := &file_update_update_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPullStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPullStarted) ProtoMessage() {}

func (x *RegistryPullStarted) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPullStarted.ProtoReflect.Descriptor instead.
func (*RegistryPullStarted) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{16}
}

func (x *RegistryPullStarted) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RegistryPullStarted) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RegistryBlobDownloading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=Digest,proto3" json:"Digest,omitempty"`          // Blob digest
	Downloaded    uint64                 `protobuf:"varint,2,opt,name=Downloaded,proto3" json:"Downloaded,omitempty"` // Downloaded byte count
	Total         *uint64                `protobuf:"varint,3,opt,name=Total,proto3,oneof" json:"Total,omitempty"`     // Total byte count, if known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryBlobDownloading) Reset() {
	*x = RegistryBlobDownloading{}
	mi := &file_update_update_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryBlobDownloading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryBlobDownloading) ProtoMessage() {}

func (x *RegistryBlobDownloading) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryBlobDownloading.ProtoReflect.Descriptor instead.
func (*RegistryBlobDownloading) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{17}
}

func (x *RegistryBlobDownloading) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegistryBlobDownloading) GetDownloaded() uint64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *RegistryBlobDownloading) GetTotal() uint64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type RegistryPullProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RegistryPullProgress_PullStarted
	//	*RegistryPullProgress_BlobDownloading
	//	*RegistryPullProgress_BlobVerified
	//	*RegistryPullProgress_ManifestWritten
	//	*RegistryPullProgress_Cancelled
	//	*RegistryPullProgress_Done
	Event         isRegistryPullProgress_Event `protobuf_oneof:"Event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPullProgress) Reset() {
	*x = RegistryPullProgress{}
	mi := &file_update_update_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPullProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPullProgress) ProtoMessage() {}

func (x *RegistryPullProgress) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPullProgress.ProtoReflect.Descriptor instead.
func (*RegistryPullProgress) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{18}
}

func (x *RegistryPullProgress) GetEvent() isRegistryPullProgress_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RegistryPullProgress) GetPullStarted() *RegistryPullStarted {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_PullStarted); ok {
			return x.PullStarted
		}
	}
	return nil
}

func (x *RegistryPullProgress) GetBlobDownloading() *RegistryBlobDownloading {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_BlobDownloading); ok {
			return x.BlobDownloading
		}
	}
	return nil
}

func (x *RegistryPullProgress) GetBlobVerified() string {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_BlobVerified); ok {
			return x.BlobVerified
		}
	}
	return ""
}

func (x *RegistryPullProgress) GetManifestWritten() string {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_ManifestWritten); ok {
			return x.ManifestWritten
		}
	}
	return ""
}

func (x *RegistryPullProgress) GetCancelled() string {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_Cancelled); ok {
			return x.Cancelled
		}
	}
	return ""
}

func (x *RegistryPullProgress) GetDone() bool {
	if x != nil {
		if x, ok := x.Event.(*RegistryPullProgress_Done); ok {
			return x.Done
		}
	}
	return false
}

type isRegistryPullProgress_Event interface {
	isRegistryPullProgress_Event()
}

type RegistryPullProgress_PullStarted struct {
	PullStarted *RegistryPullStarted `protobuf:"bytes,1,opt,name=PullStarted,proto3,oneof"` // Pull started
}

type RegistryPullProgress_BlobDownloading struct {
	BlobDownloading *RegistryBlobDownloading `protobuf:"bytes,2,opt,name=BlobDownloading,proto3,oneof"` // Blob download progress
}

type RegistryPullProgress_BlobVerified struct {
	BlobVerified string `protobuf:"bytes,3,opt,name=BlobVerified,proto3,oneof"` // Verified blob digest
}

type RegistryPullProgress_ManifestWritten struct {
	ManifestWritten string `protobuf:"bytes,4,opt,name=ManifestWritten,proto3,oneof"` // Manifest file path
}

type RegistryPullProgress_Cancelled struct {
	Cancelled string `protobuf:"bytes,5,opt,name=Cancelled,proto3,oneof"` // Cancellation reason
}

type RegistryPullProgress_Done struct {
	Done bool `protobuf:"varint,6,opt,name=Done,proto3,oneof"` // True when finished
}

func (*RegistryPullProgress_PullStarted) isRegistryPullProgress_Event() {}

func (*RegistryPullProgress_BlobDownloading) isRegistryPullProgress_Event() {}

func (*RegistryPullProgress_BlobVerified) isRegistryPullProgress_Event() {}

func (*RegistryPullProgress_ManifestWritten) isRegistryPullProgress_Event() {}

func (*RegistryPullProgress_Cancelled) isRegistryPullProgress_Event() {}

func (*RegistryPullProgress_Done) isRegistryPullProgress_Event() {}

type RegistryPullResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RegistryPullResponse_Progress
	//	*RegistryPullResponse_Result
	Update        isRegistryPullResponse_Update `protobuf_oneof:"Update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryPullResponse) Reset() {
	*x = RegistryPullResponse{}
	mi := &file_update_update_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryPullResponse) ProtoMessage() {}

func (x *RegistryPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryPullResponse.ProtoReflect.Descriptor instead.
func (*RegistryPullResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{19}
}

func (x *RegistryPullResponse) GetUpdate() isRegistryPullResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RegistryPullResponse) GetProgress() *RegistryPullProgress {
	if x != nil {
		if x, ok := x.Update.(*RegistryPullResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *RegistryPullResponse) GetResult() *RegistryPullResult {
	if x != nil {
		if x, ok := x.Update.(*RegistryPullResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRegistryPullResponse_Update interface {
	isRegistryPullResponse_Update()
}

type RegistryPullResponse_Progress struct {
	Progress *RegistryPullProgress `protobuf:"bytes,1,opt,name=Progress,proto3,oneof"` // Progress event
}

type RegistryPullResponse_Result struct {
	Result *RegistryPullResult `protobuf:"bytes,2,opt,name=Result,proto3,oneof"` // Final result
}

func (*RegistryPullResponse_Progress) isRegistryPullResponse_Update() {}

func (*RegistryPullResponse_Result) isRegistryPullResponse_Update() {}

type ImageInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      string                 `protobuf:"bytes,1,opt,name=Manifest,proto3" json:"Manifest,omitempty"` // Manifest path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInstallRequest) Reset() {
	*x = ImageInstallRequest{}
	mi := &file_update_update_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInstallRequest) ProtoMessage() {}

func (x *ImageInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInstallRequest.ProtoReflect.Descriptor instead.
func (*ImageInstallRequest) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{20}
}

func (x *ImageInstallRequest) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

type ImageInstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      bool                   `protobuf:"varint,1,opt,name=Finished,proto3" json:"Finished,omitempty"`  // True when the command completed
	Output        *string                `protobuf:"bytes,2,opt,name=Output,proto3,oneof" json:"Output,omitempty"` // Standard output from the command
	Error         *string                `protobuf:"bytes,3,opt,name=Error,proto3,oneof" json:"Error,omitempty"`   // Standard error from the command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInstallResponse) Reset() {
	*x = ImageInstallResponse{}
	mi := &file_update_update_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInstallResponse) ProtoMessage() {}

func (x *ImageInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_update_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInstallResponse.ProtoReflect.Descriptor instead.
func (*ImageInstallResponse) Descriptor() ([]byte, []int) {
	return file_update_update_proto_rawDescGZIP(), []int{21}
}

func (x *ImageInstallResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ImageInstallResponse) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *ImageInstallResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_update_update_proto protoreflect.FileDescriptor

const file_update_update_proto_rawDesc = "" +
	"\n" +
	"\x13update/update.proto\x12\x06update\"\a\n" +
	"\x05Empty\"\xa2\x02\n" +
	"\n" +
	"Generation\x12\x1e\n" +
	"\n" +
	"Generation\x18\x01 \x01(\x05R\n" +
	"Generation\x12\x12\n" +
	"\x04Date\x18\x02 \x01(\tR\x04Date\x12\"\n" +
	"\fNixosVersion\x18\x03 \x01(\tR\fNixosVersion\x12$\n" +
	"\rKernelVersion\x18\x04 \x01(\tR\rKernelVersion\x124\n" +
	"\x15ConfigurationRevision\x18\x05 \x01(\tR\x15ConfigurationRevision\x12(\n" +
	"\x0fSpecialisations\x18\x06 \x03(\tR\x0fSpecialisations\x12\x18\n" +
	"\aCurrent\x18\a \x01(\bR\aCurrent\x12\x1c\n" +
	"\tStorePath\x18\b \x01(\tR\tStorePath\"A\n" +
	"\x17ListGenerationsResponse\x12&\n" +
	"\x04List\x18\x01 \x03(\v2\x12.update.GenerationR\x04List\"J\n" +
	"\x14SetGenerationRequest\x12(\n" +
	"\x06Cachix\x18\x01 \x01(\v2\x0e.update.CachixH\x00R\x06CachixB\b\n" +
	"\x06Update\"\x89\x01\n" +
	"\x06Cachix\x12\x10\n" +
	"\x03Pin\x18\x01 \x01(\tR\x03Pin\x12#\n" +
	"\n" +
	"CachixHost\x18\x02 \x01(\tH\x00R\n" +
	"CachixHost\x88\x01\x01\x12\x14\n" +
	"\x05Cache\x18\x03 \x01(\tR\x05Cache\x12\x19\n" +
	"\x05Token\x18\x04 \x01(\tH\x01R\x05Token\x88\x01\x01B\r\n" +
	"\v_CachixHostB\b\n" +
	"\x06_Token\"\x80\x01\n" +
	"\x15SetGenerationResponse\x12\x1a\n" +
	"\bFinished\x18\x01 \x01(\bR\bFinished\x12\x1b\n" +
	"\x06Output\x18\x02 \x01(\tH\x00R\x06Output\x88\x01\x01\x12\x19\n" +
	"\x05Error\x18\x03 \x01(\tH\x01R\x05Error\x88\x01\x01B\t\n" +
	"\a_OutputB\b\n" +
	"\x06_Error\"K\n" +
	"\x11RegistryBasicAuth\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"*\n" +
	"\x12RegistryBearerAuth\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"\x86\x01\n" +
	"\x13RegistryCredentials\x121\n" +
	"\x05Basic\x18\x01 \x01(\v2\x19.update.RegistryBasicAuthH\x00R\x05Basic\x124\n" +
	"\x06Bearer\x18\x02 \x01(\v2\x1a.update.RegistryBearerAuthH\x00R\x06BearerB\x06\n" +
	"\x04Auth\"q\n" +
	"\x0fAvailableUpdate\x12\x1e\n" +
	"\n" +
	"Repository\x18\x01 \x01(\tR\n" +
	"Repository\x12\x10\n" +
	"\x03Tag\x18\x02 \x01(\tR\x03Tag\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\tR\aVersion\x12\x12\n" +
	"\x04Hash\x18\x04 \x01(\tR\x04Hash\"\xa7\x01\n" +
	"\x17RegistryDiscoverRequest\x12\x1c\n" +
	"\tReference\x18\x01 \x01(\tR\tReference\x12\x1a\n" +
	"\bInsecure\x18\x02 \x01(\bR\bInsecure\x12B\n" +
	"\vCredentials\x18\x03 \x01(\v2\x1b.update.RegistryCredentialsH\x00R\vCredentials\x88\x01\x01B\x0e\n" +
	"\f_Credentials\"G\n" +
	"\x18RegistryDiscoverResponse\x12+\n" +
	"\x04List\x18\x01 \x03(\v2\x17.update.AvailableUpdateR\x04List\"\xa8\x01\n" +
	"\x18RegistryChangelogRequest\x12\x1c\n" +
	"\tReference\x18\x01 \x01(\tR\tReference\x12\x1a\n" +
	"\bInsecure\x18\x02 \x01(\bR\bInsecure\x12B\n" +
	"\vCredentials\x18\x03 \x01(\v2\x1b.update.RegistryCredentialsH\x00R\vCredentials\x88\x01\x01B\x0e\n" +
	"\f_Credentials\"9\n" +
	"\x19RegistryChangelogResponse\x12\x1c\n" +
	"\tChangelog\x18\x01 \x01(\tR\tChangelog\"\xc5\x01\n" +
	"\x13RegistryPullRequest\x12\x1c\n" +
	"\tReference\x18\x01 \x01(\tR\tReference\x12 \n" +
	"\vDestination\x18\x02 \x01(\tR\vDestination\x12\x1a\n" +
	"\bInsecure\x18\x04 \x01(\bR\bInsecure\x12B\n" +
	"\vCredentials\x18\x05 \x01(\v2\x1b.update.RegistryCredentialsH\x00R\vCredentials\x88\x01\x01B\x0e\n" +
	"\f_Credentials\"V\n" +
	"\x12RegistryPullResult\x12\x1c\n" +
	"\tOutputDir\x18\x01 \x01(\tR\tOutputDir\x12\"\n" +
	"\fManifestPath\x18\x02 \x01(\tR\fManifestPath\"U\n" +
	"\x13RegistryPullStarted\x12\x1c\n" +
	"\tReference\x18\x01 \x01(\tR\tReference\x12 \n" +
	"\vDestination\x18\x02 \x01(\tR\vDestination\"v\n" +
	"\x17RegistryBlobDownloading\x12\x16\n" +
	"\x06Digest\x18\x01 \x01(\tR\x06Digest\x12\x1e\n" +
	"\n" +
	"Downloaded\x18\x02 \x01(\x04R\n" +
	"Downloaded\x12\x19\n" +
	"\x05Total\x18\x03 \x01(\x04H\x00R\x05Total\x88\x01\x01B\b\n" +
	"\x06_Total\"\xb5\x02\n" +
	"\x14RegistryPullProgress\x12?\n" +
	"\vPullStarted\x18\x01 \x01(\v2\x1b.update.RegistryPullStartedH\x00R\vPullStarted\x12K\n" +
	"\x0fBlobDownloading\x18\x02 \x01(\v2\x1f.update.RegistryBlobDownloadingH\x00R\x0fBlobDownloading\x12$\n" +
	"\fBlobVerified\x18\x03 \x01(\tH\x00R\fBlobVerified\x12*\n" +
	"\x0fManifestWritten\x18\x04 \x01(\tH\x00R\x0fManifestWritten\x12\x1e\n" +
	"\tCancelled\x18\x05 \x01(\tH\x00R\tCancelled\x12\x14\n" +
	"\x04Done\x18\x06 \x01(\bH\x00R\x04DoneB\a\n" +
	"\x05Event\"\x92\x01\n" +
	"\x14RegistryPullResponse\x12:\n" +
	"\bProgress\x18\x01 \x01(\v2\x1c.update.RegistryPullProgressH\x00R\bProgress\x124\n" +
	"\x06Result\x18\x02 \x01(\v2\x1a.update.RegistryPullResultH\x00R\x06ResultB\b\n" +
	"\x06Update\"1\n" +
	"\x13ImageInstallRequest\x12\x1a\n" +
	"\bManifest\x18\x01 \x01(\tR\bManifest\"\x7f\n" +
	"\x14ImageInstallResponse\x12\x1a\n" +
	"\bFinished\x18\x01 \x01(\bR\bFinished\x12\x1b\n" +
	"\x06Output\x18\x02 \x01(\tH\x00R\x06Output\x88\x01\x01\x12\x19\n" +
	"\x05Error\x18\x03 \x01(\tH\x01R\x05Error\x88\x01\x01B\t\n" +
	"\a_OutputB\b\n" +
	"\x06_Error2\xcc\x03\n" +
	"\x06Update\x12C\n" +
	"\x0fListGenerations\x12\r.update.Empty\x1a\x1f.update.ListGenerationsResponse\"\x00\x12O\n" +
	"\bDiscover\x12\x1f.update.RegistryDiscoverRequest\x1a .update.RegistryDiscoverResponse\"\x00\x12R\n" +
	"\tChangelog\x12 .update.RegistryChangelogRequest\x1a!.update.RegistryChangelogResponse\"\x00\x12E\n" +
	"\x04Pull\x12\x1b.update.RegistryPullRequest\x1a\x1c.update.RegistryPullResponse\"\x000\x01\x12M\n" +
	"\fImageInstall\x12\x1b.update.ImageInstallRequest\x1a\x1c.update.ImageInstallResponse\"\x000\x01\x12B\n" +
	"\rInstallCachix\x12\x0e.update.Cachix\x1a\x1d.update.SetGenerationResponse\"\x000\x01B\x19Z\x17givc/modules/api/updateb\x06proto3"

var (
	file_update_update_proto_rawDescOnce sync.Once
	file_update_update_proto_rawDescData []byte
)

func file_update_update_proto_rawDescGZIP() []byte {
	file_update_update_proto_rawDescOnce.Do(func() {
		file_update_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_update_proto_rawDesc), len(file_update_update_proto_rawDesc)))
	})
	return file_update_update_proto_rawDescData
}

var file_update_update_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_update_update_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: update.Empty
	(*Generation)(nil),                // 1: update.Generation
	(*ListGenerationsResponse)(nil),   // 2: update.ListGenerationsResponse
	(*SetGenerationRequest)(nil),      // 3: update.SetGenerationRequest
	(*Cachix)(nil),                    // 4: update.Cachix
	(*SetGenerationResponse)(nil),     // 5: update.SetGenerationResponse
	(*RegistryBasicAuth)(nil),         // 6: update.RegistryBasicAuth
	(*RegistryBearerAuth)(nil),        // 7: update.RegistryBearerAuth
	(*RegistryCredentials)(nil),       // 8: update.RegistryCredentials
	(*AvailableUpdate)(nil),           // 9: update.AvailableUpdate
	(*RegistryDiscoverRequest)(nil),   // 10: update.RegistryDiscoverRequest
	(*RegistryDiscoverResponse)(nil),  // 11: update.RegistryDiscoverResponse
	(*RegistryChangelogRequest)(nil),  // 12: update.RegistryChangelogRequest
	(*RegistryChangelogResponse)(nil), // 13: update.RegistryChangelogResponse
	(*RegistryPullRequest)(nil),       // 14: update.RegistryPullRequest
	(*RegistryPullResult)(nil),        // 15: update.RegistryPullResult
	(*RegistryPullStarted)(nil),       // 16: update.RegistryPullStarted
	(*RegistryBlobDownloading)(nil),   // 17: update.RegistryBlobDownloading
	(*RegistryPullProgress)(nil),      // 18: update.RegistryPullProgress
	(*RegistryPullResponse)(nil),      // 19: update.RegistryPullResponse
	(*ImageInstallRequest)(nil),       // 20: update.ImageInstallRequest
	(*ImageInstallResponse)(nil),      // 21: update.ImageInstallResponse
}
var file_update_update_proto_depIdxs = []int32{
	1,  // 0: update.ListGenerationsResponse.List:type_name -> update.Generation
	4,  // 1: update.SetGenerationRequest.Cachix:type_name -> update.Cachix
	6,  // 2: update.RegistryCredentials.Basic:type_name -> update.RegistryBasicAuth
	7,  // 3: update.RegistryCredentials.Bearer:type_name -> update.RegistryBearerAuth
	8,  // 4: update.RegistryDiscoverRequest.Credentials:type_name -> update.RegistryCredentials
	9,  // 5: update.RegistryDiscoverResponse.List:type_name -> update.AvailableUpdate
	8,  // 6: update.RegistryChangelogRequest.Credentials:type_name -> update.RegistryCredentials
	8,  // 7: update.RegistryPullRequest.Credentials:type_name -> update.RegistryCredentials
	16, // 8: update.RegistryPullProgress.PullStarted:type_name -> update.RegistryPullStarted
	17, // 9: update.RegistryPullProgress.BlobDownloading:type_name -> update.RegistryBlobDownloading
	18, // 10: update.RegistryPullResponse.Progress:type_name -> update.RegistryPullProgress
	15, // 11: update.RegistryPullResponse.Result:type_name -> update.RegistryPullResult
	0,  // 12: update.Update.ListGenerations:input_type -> update.Empty
	10, // 13: update.Update.Discover:input_type -> update.RegistryDiscoverRequest
	12, // 14: update.Update.Changelog:input_type -> update.RegistryChangelogRequest
	14, // 15: update.Update.Pull:input_type -> update.RegistryPullRequest
	20, // 16: update.Update.ImageInstall:input_type -> update.ImageInstallRequest
	4,  // 17: update.Update.InstallCachix:input_type -> update.Cachix
	2,  // 18: update.Update.ListGenerations:output_type -> update.ListGenerationsResponse
	11, // 19: update.Update.Discover:output_type -> update.RegistryDiscoverResponse
	13, // 20: update.Update.Changelog:output_type -> update.RegistryChangelogResponse
	19, // 21: update.Update.Pull:output_type -> update.RegistryPullResponse
	21, // 22: update.Update.ImageInstall:output_type -> update.ImageInstallResponse
	5,  // 23: update.Update.InstallCachix:output_type -> update.SetGenerationResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_update_update_proto_init() }
func file_update_update_proto_init() {
	if File_update_update_proto != nil {
		return
	}
	file_update_update_proto_msgTypes[3].OneofWrappers = []any{
		(*SetGenerationRequest_Cachix)(nil),
	}
	file_update_update_proto_msgTypes[4].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[5].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[8].OneofWrappers = []any{
		(*RegistryCredentials_Basic)(nil),
		(*RegistryCredentials_Bearer)(nil),
	}
	file_update_update_proto_msgTypes[10].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[12].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[14].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[17].OneofWrappers = []any{}
	file_update_update_proto_msgTypes[18].OneofWrappers = []any{
		(*RegistryPullProgress_PullStarted)(nil),
		(*RegistryPullProgress_BlobDownloading)(nil),
		(*RegistryPullProgress_BlobVerified)(nil),
		(*RegistryPullProgress_ManifestWritten)(nil),
		(*RegistryPullProgress_Cancelled)(nil),
		(*RegistryPullProgress_Done)(nil),
	}
	file_update_update_proto_msgTypes[19].OneofWrappers = []any{
		(*RegistryPullResponse_Progress)(nil),
		(*RegistryPullResponse_Result)(nil),
	}
	file_update_update_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_update_proto_rawDesc), len(file_update_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_update_update_proto_goTypes,
		DependencyIndexes: file_update_update_proto_depIdxs,
		MessageInfos:      file_update_update_proto_msgTypes,
	}.Build()
	File_update_update_proto = out.File
	file_update_update_proto_goTypes = nil
	file_update_update_proto_depIdxs = nil
}
