// Copyright 2024 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: hwid/hwid.proto

package hwid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HwidService_GetHwId_FullMethodName = "/hwid.HwidService/GetHwId"
)

// HwidServiceClient is the client API for HwidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HwidServiceClient interface {
	GetHwId(ctx context.Context, in *HwIdRequest, opts ...grpc.CallOption) (*HwIdResponse, error)
}

type hwidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHwidServiceClient(cc grpc.ClientConnInterface) HwidServiceClient {
	return &hwidServiceClient{cc}
}

func (c *hwidServiceClient) GetHwId(ctx context.Context, in *HwIdRequest, opts ...grpc.CallOption) (*HwIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HwIdResponse)
	err := c.cc.Invoke(ctx, HwidService_GetHwId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HwidServiceServer is the server API for HwidService service.
// All implementations must embed UnimplementedHwidServiceServer
// for forward compatibility.
type HwidServiceServer interface {
	GetHwId(context.Context, *HwIdRequest) (*HwIdResponse, error)
	mustEmbedUnimplementedHwidServiceServer()
}

// UnimplementedHwidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHwidServiceServer struct{}

func (UnimplementedHwidServiceServer) GetHwId(context.Context, *HwIdRequest) (*HwIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHwId not implemented")
}
func (UnimplementedHwidServiceServer) mustEmbedUnimplementedHwidServiceServer() {}
func (UnimplementedHwidServiceServer) testEmbeddedByValue()                     {}

// UnsafeHwidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HwidServiceServer will
// result in compilation errors.
type UnsafeHwidServiceServer interface {
	mustEmbedUnimplementedHwidServiceServer()
}

func RegisterHwidServiceServer(s grpc.ServiceRegistrar, srv HwidServiceServer) {
	// If the following call pancis, it indicates UnimplementedHwidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HwidService_ServiceDesc, srv)
}

func _HwidService_GetHwId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HwIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HwidServiceServer).GetHwId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HwidService_GetHwId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HwidServiceServer).GetHwId(ctx, req.(*HwIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HwidService_ServiceDesc is the grpc.ServiceDesc for HwidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HwidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hwid.HwidService",
	HandlerType: (*HwidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHwId",
			Handler:    _HwidService_GetHwId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hwid/hwid.proto",
}
