// Copyright 2024 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.1
// source: hwid/hwid.proto

package hwid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HwIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HwIdRequest) Reset() {
	*x = HwIdRequest{}
	mi := &file_hwid_hwid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HwIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HwIdRequest) ProtoMessage() {}

func (x *HwIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hwid_hwid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HwIdRequest.ProtoReflect.Descriptor instead.
func (*HwIdRequest) Descriptor() ([]byte, []int) {
	return file_hwid_hwid_proto_rawDescGZIP(), []int{0}
}

type HwIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HwIdResponse) Reset() {
	*x = HwIdResponse{}
	mi := &file_hwid_hwid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HwIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HwIdResponse) ProtoMessage() {}

func (x *HwIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hwid_hwid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HwIdResponse.ProtoReflect.Descriptor instead.
func (*HwIdResponse) Descriptor() ([]byte, []int) {
	return file_hwid_hwid_proto_rawDescGZIP(), []int{1}
}

func (x *HwIdResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

var File_hwid_hwid_proto protoreflect.FileDescriptor

var file_hwid_hwid_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x77, 0x69, 0x64, 0x2f, 0x68, 0x77, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x68, 0x77, 0x69, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x48, 0x77, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x0c, 0x48, 0x77, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x32, 0x41, 0x0a, 0x0b, 0x48, 0x77, 0x69, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x77, 0x49, 0x64,
	0x12, 0x11, 0x2e, 0x68, 0x77, 0x69, 0x64, 0x2e, 0x48, 0x77, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x77, 0x69, 0x64, 0x2e, 0x48, 0x77, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x69, 0x76,
	0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x77,
	0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hwid_hwid_proto_rawDescOnce sync.Once
	file_hwid_hwid_proto_rawDescData = file_hwid_hwid_proto_rawDesc
)

func file_hwid_hwid_proto_rawDescGZIP() []byte {
	file_hwid_hwid_proto_rawDescOnce.Do(func() {
		file_hwid_hwid_proto_rawDescData = protoimpl.X.CompressGZIP(file_hwid_hwid_proto_rawDescData)
	})
	return file_hwid_hwid_proto_rawDescData
}

var file_hwid_hwid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hwid_hwid_proto_goTypes = []any{
	(*HwIdRequest)(nil),  // 0: hwid.HwIdRequest
	(*HwIdResponse)(nil), // 1: hwid.HwIdResponse
}
var file_hwid_hwid_proto_depIdxs = []int32{
	0, // 0: hwid.HwidService.GetHwId:input_type -> hwid.HwIdRequest
	1, // 1: hwid.HwidService.GetHwId:output_type -> hwid.HwIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hwid_hwid_proto_init() }
func file_hwid_hwid_proto_init() {
	if File_hwid_hwid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hwid_hwid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hwid_hwid_proto_goTypes,
		DependencyIndexes: file_hwid_hwid_proto_depIdxs,
		MessageInfos:      file_hwid_hwid_proto_msgTypes,
	}.Build()
	File_hwid_hwid_proto = out.File
	file_hwid_hwid_proto_rawDesc = nil
	file_hwid_hwid_proto_goTypes = nil
	file_hwid_hwid_proto_depIdxs = nil
}
