// Copyright 2024 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: locale/locale.proto

package locale

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocaleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=Locale,proto3" json:"Locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleMessage) Reset() {
	*x = LocaleMessage{}
	mi := &file_locale_locale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleMessage) ProtoMessage() {}

func (x *LocaleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_locale_locale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleMessage.ProtoReflect.Descriptor instead.
func (*LocaleMessage) Descriptor() ([]byte, []int) {
	return file_locale_locale_proto_rawDescGZIP(), []int{0}
}

func (x *LocaleMessage) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type TimezoneMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=Timezone,proto3" json:"Timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimezoneMessage) Reset() {
	*x = TimezoneMessage{}
	mi := &file_locale_locale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimezoneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimezoneMessage) ProtoMessage() {}

func (x *TimezoneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_locale_locale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimezoneMessage.ProtoReflect.Descriptor instead.
func (*TimezoneMessage) Descriptor() ([]byte, []int) {
	return file_locale_locale_proto_rawDescGZIP(), []int{1}
}

func (x *TimezoneMessage) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_locale_locale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_locale_locale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_locale_locale_proto_rawDescGZIP(), []int{2}
}

var File_locale_locale_proto protoreflect.FileDescriptor

const file_locale_locale_proto_rawDesc = "" +
	"\n" +
	"\x13locale/locale.proto\x12\x06locale\"'\n" +
	"\rLocaleMessage\x12\x16\n" +
	"\x06Locale\x18\x01 \x01(\tR\x06Locale\"-\n" +
	"\x0fTimezoneMessage\x12\x1a\n" +
	"\bTimezone\x18\x01 \x01(\tR\bTimezone\"\a\n" +
	"\x05Empty2|\n" +
	"\fLocaleClient\x123\n" +
	"\tLocaleSet\x12\x15.locale.LocaleMessage\x1a\r.locale.Empty\"\x00\x127\n" +
	"\vTimezoneSet\x12\x17.locale.TimezoneMessage\x1a\r.locale.Empty\"\x00B\x19Z\x17givc/modules/api/localeb\x06proto3"

var (
	file_locale_locale_proto_rawDescOnce sync.Once
	file_locale_locale_proto_rawDescData []byte
)

func file_locale_locale_proto_rawDescGZIP() []byte {
	file_locale_locale_proto_rawDescOnce.Do(func() {
		file_locale_locale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locale_locale_proto_rawDesc), len(file_locale_locale_proto_rawDesc)))
	})
	return file_locale_locale_proto_rawDescData
}

var file_locale_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_locale_locale_proto_goTypes = []any{
	(*LocaleMessage)(nil),   // 0: locale.LocaleMessage
	(*TimezoneMessage)(nil), // 1: locale.TimezoneMessage
	(*Empty)(nil),           // 2: locale.Empty
}
var file_locale_locale_proto_depIdxs = []int32{
	0, // 0: locale.LocaleClient.LocaleSet:input_type -> locale.LocaleMessage
	1, // 1: locale.LocaleClient.TimezoneSet:input_type -> locale.TimezoneMessage
	2, // 2: locale.LocaleClient.LocaleSet:output_type -> locale.Empty
	2, // 3: locale.LocaleClient.TimezoneSet:output_type -> locale.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_locale_locale_proto_init() }
func file_locale_locale_proto_init() {
	if File_locale_locale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locale_locale_proto_rawDesc), len(file_locale_locale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locale_locale_proto_goTypes,
		DependencyIndexes: file_locale_locale_proto_depIdxs,
		MessageInfos:      file_locale_locale_proto_msgTypes,
	}.Build()
	File_locale_locale_proto = out.File
	file_locale_locale_proto_goTypes = nil
	file_locale_locale_proto_depIdxs = nil
}
