[package]
authors = ["Alexander Nikolaev <alexander.nikolaev@unikie.com>"]
edition = "2024"
license = "Apache 2.0"
name = "givc-common"
publish = false
version = "0.0.1"

[dependencies]
anyhow.workspace = true
glib = { version = "*", optional = true, features = [] }
hyper-util.workspace = true
prost = "0.14"
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
rustls = { workspace = true, features = ["ring"] }
rustls-pemfile.workspace = true
spiffe = { workspace = true, features = ["x509-source"] }
spiffe-rustls.workspace = true
tokio = { workspace = true, features = [
  "net",
  "io-util",
  "sync",
  "rt",
  "time",
] }
tokio-listener.workspace = true
tokio-rustls.workspace = true
tokio-stream.workspace = true
tokio-vsock.workspace = true
tonic = { workspace = true, features = ["tls-aws-lc"] }
tonic-prost.workspace = true
tower.workspace = true
tracing.workspace = true
[build-dependencies]
tonic-prost-build.workspace = true

[features]
glib = ["dep:glib"]

[package.metadata.cargo-machete]
ignored = ["prost", "tonic-prost"]
