// Admin Service API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: admin/admin.proto

package admin

import (
	context "context"
	notify "givc/modules/api/notify"
	stats "givc/modules/api/stats"
	systemd "givc/modules/api/systemd"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_RegisterService_FullMethodName   = "/admin.AdminService/RegisterService"
	AdminService_StartApplication_FullMethodName  = "/admin.AdminService/StartApplication"
	AdminService_StartVM_FullMethodName           = "/admin.AdminService/StartVM"
	AdminService_StartService_FullMethodName      = "/admin.AdminService/StartService"
	AdminService_PauseApplication_FullMethodName  = "/admin.AdminService/PauseApplication"
	AdminService_ResumeApplication_FullMethodName = "/admin.AdminService/ResumeApplication"
	AdminService_StopApplication_FullMethodName   = "/admin.AdminService/StopApplication"
	AdminService_SetLocale_FullMethodName         = "/admin.AdminService/SetLocale"
	AdminService_SetTimezone_FullMethodName       = "/admin.AdminService/SetTimezone"
	AdminService_Poweroff_FullMethodName          = "/admin.AdminService/Poweroff"
	AdminService_Reboot_FullMethodName            = "/admin.AdminService/Reboot"
	AdminService_Suspend_FullMethodName           = "/admin.AdminService/Suspend"
	AdminService_Wakeup_FullMethodName            = "/admin.AdminService/Wakeup"
	AdminService_GetUnitStatus_FullMethodName     = "/admin.AdminService/GetUnitStatus"
	AdminService_GetStats_FullMethodName          = "/admin.AdminService/GetStats"
	AdminService_QueryList_FullMethodName         = "/admin.AdminService/QueryList"
	AdminService_Watch_FullMethodName             = "/admin.AdminService/Watch"
	AdminService_ListGenerations_FullMethodName   = "/admin.AdminService/ListGenerations"
	AdminService_SetGeneration_FullMethodName     = "/admin.AdminService/SetGeneration"
	AdminService_NotifyUser_FullMethodName        = "/admin.AdminService/NotifyUser"
	AdminService_PolicyQuery_FullMethodName       = "/admin.AdminService/PolicyQuery"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// Register a remote agent or service
	RegisterService(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryResponse, error)
	// Start a remote application
	StartApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Start a VM
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Start a remote service
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Pause (freeze) a remote application
	PauseApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error)
	// Resume (un-freeze) a remote application
	ResumeApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error)
	// Stop a remote application
	StopApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error)
	// Set locale (broadcasted across system)
	SetLocale(ctx context.Context, in *LocaleRequest, opts ...grpc.CallOption) (*Empty, error)
	// Set timezone (broadcasted across system)
	SetTimezone(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*Empty, error)
	// System poweroff command
	Poweroff(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// System reboot command
	Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// System suspend command
	Suspend(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// System wakeup command
	Wakeup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Get systemd unit status
	GetUnitStatus(ctx context.Context, in *UnitStatusRequest, opts ...grpc.CallOption) (*systemd.UnitStatus, error)
	// Get stats information
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*stats.StatsResponse, error)
	// Get list of monitored units
	QueryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueryListResponse, error)
	// Get stream of monitored units
	Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchItem], error)
	// OTA
	ListGenerations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListGenerationsResponse, error)
	SetGeneration(ctx context.Context, in *SetGenerationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SetGenerationResponse], error)
	// Send user notification
	NotifyUser(ctx context.Context, in *UserNotificationRequest, opts ...grpc.CallOption) (*notify.Status, error)
	// Policy Query
	PolicyQuery(ctx context.Context, in *PolicyQueryRequest, opts ...grpc.CallOption) (*PolicyQueryResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) RegisterService(ctx context.Context, in *RegistryRequest, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, AdminService_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, AdminService_StartApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, AdminService_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, AdminService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PauseApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationResponse)
	err := c.cc.Invoke(ctx, AdminService_PauseApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResumeApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationResponse)
	err := c.cc.Invoke(ctx, AdminService_ResumeApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopApplication(ctx context.Context, in *ApplicationRequest, opts ...grpc.CallOption) (*ApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationResponse)
	err := c.cc.Invoke(ctx, AdminService_StopApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetLocale(ctx context.Context, in *LocaleRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_SetLocale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetTimezone(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_SetTimezone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Poweroff(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_Poweroff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Suspend(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_Suspend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Wakeup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_Wakeup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUnitStatus(ctx context.Context, in *UnitStatusRequest, opts ...grpc.CallOption) (*systemd.UnitStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(systemd.UnitStatus)
	err := c.cc.Invoke(ctx, AdminService_GetUnitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*stats.StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(stats.StatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) QueryList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListResponse)
	err := c.cc.Invoke(ctx, AdminService_QueryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Watch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WatchItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchClient = grpc.ServerStreamingClient[WatchItem]

func (c *adminServiceClient) ListGenerations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListGenerationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGenerationsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetGeneration(ctx context.Context, in *SetGenerationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SetGenerationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[1], AdminService_SetGeneration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetGenerationRequest, SetGenerationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_SetGenerationClient = grpc.ServerStreamingClient[SetGenerationResponse]

func (c *adminServiceClient) NotifyUser(ctx context.Context, in *UserNotificationRequest, opts ...grpc.CallOption) (*notify.Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(notify.Status)
	err := c.cc.Invoke(ctx, AdminService_NotifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PolicyQuery(ctx context.Context, in *PolicyQueryRequest, opts ...grpc.CallOption) (*PolicyQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyQueryResponse)
	err := c.cc.Invoke(ctx, AdminService_PolicyQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	// Register a remote agent or service
	RegisterService(context.Context, *RegistryRequest) (*RegistryResponse, error)
	// Start a remote application
	StartApplication(context.Context, *ApplicationRequest) (*StartResponse, error)
	// Start a VM
	StartVM(context.Context, *StartVMRequest) (*StartResponse, error)
	// Start a remote service
	StartService(context.Context, *StartServiceRequest) (*StartResponse, error)
	// Pause (freeze) a remote application
	PauseApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error)
	// Resume (un-freeze) a remote application
	ResumeApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error)
	// Stop a remote application
	StopApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error)
	// Set locale (broadcasted across system)
	SetLocale(context.Context, *LocaleRequest) (*Empty, error)
	// Set timezone (broadcasted across system)
	SetTimezone(context.Context, *TimezoneRequest) (*Empty, error)
	// System poweroff command
	Poweroff(context.Context, *Empty) (*Empty, error)
	// System reboot command
	Reboot(context.Context, *Empty) (*Empty, error)
	// System suspend command
	Suspend(context.Context, *Empty) (*Empty, error)
	// System wakeup command
	Wakeup(context.Context, *Empty) (*Empty, error)
	// Get systemd unit status
	GetUnitStatus(context.Context, *UnitStatusRequest) (*systemd.UnitStatus, error)
	// Get stats information
	GetStats(context.Context, *StatsRequest) (*stats.StatsResponse, error)
	// Get list of monitored units
	QueryList(context.Context, *Empty) (*QueryListResponse, error)
	// Get stream of monitored units
	Watch(*Empty, grpc.ServerStreamingServer[WatchItem]) error
	// OTA
	ListGenerations(context.Context, *Empty) (*ListGenerationsResponse, error)
	SetGeneration(*SetGenerationRequest, grpc.ServerStreamingServer[SetGenerationResponse]) error
	// Send user notification
	NotifyUser(context.Context, *UserNotificationRequest) (*notify.Status, error)
	// Policy Query
	PolicyQuery(context.Context, *PolicyQueryRequest) (*PolicyQueryResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) RegisterService(context.Context, *RegistryRequest) (*RegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedAdminServiceServer) StartApplication(context.Context, *ApplicationRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartApplication not implemented")
}
func (UnimplementedAdminServiceServer) StartVM(context.Context, *StartVMRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedAdminServiceServer) StartService(context.Context, *StartServiceRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedAdminServiceServer) PauseApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseApplication not implemented")
}
func (UnimplementedAdminServiceServer) ResumeApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeApplication not implemented")
}
func (UnimplementedAdminServiceServer) StopApplication(context.Context, *ApplicationRequest) (*ApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopApplication not implemented")
}
func (UnimplementedAdminServiceServer) SetLocale(context.Context, *LocaleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocale not implemented")
}
func (UnimplementedAdminServiceServer) SetTimezone(context.Context, *TimezoneRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimezone not implemented")
}
func (UnimplementedAdminServiceServer) Poweroff(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poweroff not implemented")
}
func (UnimplementedAdminServiceServer) Reboot(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedAdminServiceServer) Suspend(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suspend not implemented")
}
func (UnimplementedAdminServiceServer) Wakeup(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Wakeup not implemented")
}
func (UnimplementedAdminServiceServer) GetUnitStatus(context.Context, *UnitStatusRequest) (*systemd.UnitStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnitStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetStats(context.Context, *StatsRequest) (*stats.StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAdminServiceServer) QueryList(context.Context, *Empty) (*QueryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryList not implemented")
}
func (UnimplementedAdminServiceServer) Watch(*Empty, grpc.ServerStreamingServer[WatchItem]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAdminServiceServer) ListGenerations(context.Context, *Empty) (*ListGenerationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGenerations not implemented")
}
func (UnimplementedAdminServiceServer) SetGeneration(*SetGenerationRequest, grpc.ServerStreamingServer[SetGenerationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SetGeneration not implemented")
}
func (UnimplementedAdminServiceServer) NotifyUser(context.Context, *UserNotificationRequest) (*notify.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUser not implemented")
}
func (UnimplementedAdminServiceServer) PolicyQuery(context.Context, *PolicyQueryRequest) (*PolicyQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PolicyQuery not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RegisterService(ctx, req.(*RegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartApplication(ctx, req.(*ApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PauseApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PauseApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PauseApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PauseApplication(ctx, req.(*ApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResumeApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResumeApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResumeApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResumeApplication(ctx, req.(*ApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StopApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopApplication(ctx, req.(*ApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetLocale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetLocale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetLocale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetLocale(ctx, req.(*LocaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetTimezone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetTimezone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetTimezone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetTimezone(ctx, req.(*TimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Poweroff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Poweroff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Poweroff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Poweroff(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Reboot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Suspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Suspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Suspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Suspend(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Wakeup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Wakeup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Wakeup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Wakeup(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUnitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUnitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUnitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUnitStatus(ctx, req.(*UnitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_QueryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).QueryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_QueryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).QueryList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).Watch(m, &grpc.GenericServerStream[Empty, WatchItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchServer = grpc.ServerStreamingServer[WatchItem]

func _AdminService_ListGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListGenerations(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetGeneration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetGenerationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).SetGeneration(m, &grpc.GenericServerStream[SetGenerationRequest, SetGenerationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_SetGenerationServer = grpc.ServerStreamingServer[SetGenerationResponse]

func _AdminService_NotifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).NotifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_NotifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).NotifyUser(ctx, req.(*UserNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PolicyQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PolicyQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PolicyQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PolicyQuery(ctx, req.(*PolicyQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _AdminService_RegisterService_Handler,
		},
		{
			MethodName: "StartApplication",
			Handler:    _AdminService_StartApplication_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _AdminService_StartVM_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _AdminService_StartService_Handler,
		},
		{
			MethodName: "PauseApplication",
			Handler:    _AdminService_PauseApplication_Handler,
		},
		{
			MethodName: "ResumeApplication",
			Handler:    _AdminService_ResumeApplication_Handler,
		},
		{
			MethodName: "StopApplication",
			Handler:    _AdminService_StopApplication_Handler,
		},
		{
			MethodName: "SetLocale",
			Handler:    _AdminService_SetLocale_Handler,
		},
		{
			MethodName: "SetTimezone",
			Handler:    _AdminService_SetTimezone_Handler,
		},
		{
			MethodName: "Poweroff",
			Handler:    _AdminService_Poweroff_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _AdminService_Reboot_Handler,
		},
		{
			MethodName: "Suspend",
			Handler:    _AdminService_Suspend_Handler,
		},
		{
			MethodName: "Wakeup",
			Handler:    _AdminService_Wakeup_Handler,
		},
		{
			MethodName: "GetUnitStatus",
			Handler:    _AdminService_GetUnitStatus_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _AdminService_GetStats_Handler,
		},
		{
			MethodName: "QueryList",
			Handler:    _AdminService_QueryList_Handler,
		},
		{
			MethodName: "ListGenerations",
			Handler:    _AdminService_ListGenerations_Handler,
		},
		{
			MethodName: "NotifyUser",
			Handler:    _AdminService_NotifyUser_Handler,
		},
		{
			MethodName: "PolicyQuery",
			Handler:    _AdminService_PolicyQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _AdminService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetGeneration",
			Handler:       _AdminService_SetGeneration_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "admin/admin.proto",
}
