// Admin Service API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: admin/admin.proto

package admin

import (
	locale "givc/modules/api/locale"
	notify "givc/modules/api/notify"
	stats "givc/modules/api/stats"
	systemd "givc/modules/api/systemd"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=Protocol,proto3" json:"Protocol,omitempty"` // Protocol identifier, one of tcp, vsock, unix
	Address       string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`   // IPv4 address, vsock CID, or unix socket path
	Port          string                 `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`         // Port number
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`         // Host name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TransportConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TransportConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransportConfig) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *TransportConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`           // Component name for registry entry
	Parent        string                 `protobuf:"bytes,2,opt,name=Parent,proto3" json:"Parent,omitempty"`       // Parent component identifier (registry name)
	Type          uint32                 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`          // Component type
	Transport     *TransportConfig       `protobuf:"bytes,4,opt,name=Transport,proto3" json:"Transport,omitempty"` // `TransportConfig`
	State         *systemd.UnitStatus    `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`         // Unit status of the component (systemd)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRequest) Reset() {
	*x = RegistryRequest{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequest) ProtoMessage() {}

func (x *RegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequest.ProtoReflect.Descriptor instead.
func (*RegistryRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *RegistryRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RegistryRequest) GetTransport() *TransportConfig {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *RegistryRequest) GetState() *systemd.UnitStatus {
	if x != nil {
		return x.State
	}
	return nil
}

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error,proto3,oneof" json:"Error,omitempty"` // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`     // Application name
	VmName        *string                `protobuf:"bytes,2,opt,name=VmName,proto3,oneof" json:"VmName,omitempty"` // Name of the VM hosting the application
	Args          []string               `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`           // Application arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationRequest) Reset() {
	*x = ApplicationRequest{}
	mi := &file_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationRequest) ProtoMessage() {}

func (x *ApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationRequest.ProtoReflect.Descriptor instead.
func (*ApplicationRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApplicationRequest) GetVmName() string {
	if x != nil && x.VmName != nil {
		return *x.VmName
	}
	return ""
}

func (x *ApplicationRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"` // VM name to query status information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *StatsRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"` // Name of the VM to start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *StartVMRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"` // Name of the service to start
	VmName        string                 `protobuf:"bytes,2,opt,name=VmName,proto3" json:"VmName,omitempty"`           // Name of the VM hosting service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *StartServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StartServiceRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryId    string                 `protobuf:"bytes,1,opt,name=registryId,proto3" json:"registryId,omitempty"` // Registry ID for newly started app, service or vm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *StartResponse) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

type ApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdStatus     string                 `protobuf:"bytes,1,opt,name=CmdStatus,proto3" json:"CmdStatus,omitempty"` // Status of the RPC command
	AppStatus     string                 `protobuf:"bytes,2,opt,name=AppStatus,proto3" json:"AppStatus,omitempty"` // Status of the application
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationResponse) Reset() {
	*x = ApplicationResponse{}
	mi := &file_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationResponse) ProtoMessage() {}

func (x *ApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationResponse.ProtoReflect.Descriptor instead.
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ApplicationResponse) GetCmdStatus() string {
	if x != nil {
		return x.CmdStatus
	}
	return ""
}

func (x *ApplicationResponse) GetAppStatus() string {
	if x != nil {
		return x.AppStatus
	}
	return ""
}

type UnitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"`     // Name of the VM hosting the unit
	UnitName      string                 `protobuf:"bytes,2,opt,name=UnitName,proto3" json:"UnitName,omitempty"` // Name of the unit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitStatusRequest) Reset() {
	*x = UnitStatusRequest{}
	mi := &file_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitStatusRequest) ProtoMessage() {}

func (x *UnitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitStatusRequest.ProtoReflect.Descriptor instead.
func (*UnitStatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UnitStatusRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *UnitStatusRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

type PolicyQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	PolicyPath    string                 `protobuf:"bytes,2,opt,name=PolicyPath,proto3" json:"PolicyPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyQueryRequest) Reset() {
	*x = PolicyQueryRequest{}
	mi := &file_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyQueryRequest) ProtoMessage() {}

func (x *PolicyQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyQueryRequest.ProtoReflect.Descriptor instead.
func (*PolicyQueryRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PolicyQueryRequest) GetPolicyPath() string {
	if x != nil {
		return x.PolicyPath
	}
	return ""
}

type PolicyQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyQueryResponse) Reset() {
	*x = PolicyQueryResponse{}
	mi := &file_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyQueryResponse) ProtoMessage() {}

func (x *PolicyQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyQueryResponse.ProtoReflect.Descriptor instead.
func (*PolicyQueryResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyQueryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{12}
}

type QueryListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                 // Name of the unit
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`   // Description of the unit
	VmStatus      string                 `protobuf:"bytes,3,opt,name=VmStatus,proto3" json:"VmStatus,omitempty"`         // Status of the VM hosting the unit
	TrustLevel    string                 `protobuf:"bytes,4,opt,name=TrustLevel,proto3" json:"TrustLevel,omitempty"`     // Trust Level (future use)
	VmType        string                 `protobuf:"bytes,5,opt,name=VmType,proto3" json:"VmType,omitempty"`             // Type of the VM (future use)
	ServiceType   string                 `protobuf:"bytes,6,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"`   // Type of the service (future use)
	VmName        *string                `protobuf:"bytes,7,opt,name=VmName,proto3,oneof" json:"VmName,omitempty"`       // Name of the VM to query; None for host running services
	AgentName     *string                `protobuf:"bytes,8,opt,name=AgentName,proto3,oneof" json:"AgentName,omitempty"` // Name of the managing agent; None for agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListItem) Reset() {
	*x = QueryListItem{}
	mi := &file_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListItem) ProtoMessage() {}

func (x *QueryListItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListItem.ProtoReflect.Descriptor instead.
func (*QueryListItem) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *QueryListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QueryListItem) GetVmStatus() string {
	if x != nil {
		return x.VmStatus
	}
	return ""
}

func (x *QueryListItem) GetTrustLevel() string {
	if x != nil {
		return x.TrustLevel
	}
	return ""
}

func (x *QueryListItem) GetVmType() string {
	if x != nil {
		return x.VmType
	}
	return ""
}

func (x *QueryListItem) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *QueryListItem) GetVmName() string {
	if x != nil && x.VmName != nil {
		return *x.VmName
	}
	return ""
}

func (x *QueryListItem) GetAgentName() string {
	if x != nil && x.AgentName != nil {
		return *x.AgentName
	}
	return ""
}

type QueryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*QueryListItem       `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // List of query responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListResponse) Reset() {
	*x = QueryListResponse{}
	mi := &file_admin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListResponse) ProtoMessage() {}

func (x *QueryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListResponse.ProtoReflect.Descriptor instead.
func (*QueryListResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *QueryListResponse) GetList() []*QueryListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type WatchItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*WatchItem_Initial
	//	*WatchItem_Added
	//	*WatchItem_Updated
	//	*WatchItem_Removed
	Status        isWatchItem_Status `protobuf_oneof:"Status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItem) Reset() {
	*x = WatchItem{}
	mi := &file_admin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItem) ProtoMessage() {}

func (x *WatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItem.ProtoReflect.Descriptor instead.
func (*WatchItem) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *WatchItem) GetStatus() isWatchItem_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WatchItem) GetInitial() *QueryListResponse {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Initial); ok {
			return x.Initial
		}
	}
	return nil
}

func (x *WatchItem) GetAdded() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Added); ok {
			return x.Added
		}
	}
	return nil
}

func (x *WatchItem) GetUpdated() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *WatchItem) GetRemoved() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

type isWatchItem_Status interface {
	isWatchItem_Status()
}

type WatchItem_Initial struct {
	Initial *QueryListResponse `protobuf:"bytes,1,opt,name=Initial,proto3,oneof"`
}

type WatchItem_Added struct {
	Added *QueryListItem `protobuf:"bytes,2,opt,name=Added,proto3,oneof"`
}

type WatchItem_Updated struct {
	Updated *QueryListItem `protobuf:"bytes,3,opt,name=Updated,proto3,oneof"`
}

type WatchItem_Removed struct {
	Removed *QueryListItem `protobuf:"bytes,4,opt,name=Removed,proto3,oneof"`
}

func (*WatchItem_Initial) isWatchItem_Status() {}

func (*WatchItem_Added) isWatchItem_Status() {}

func (*WatchItem_Updated) isWatchItem_Status() {}

func (*WatchItem_Removed) isWatchItem_Status() {}

type LocaleRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Assignments   []*locale.LocaleAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"` // List of locale assignments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleRequest) Reset() {
	*x = LocaleRequest{}
	mi := &file_admin_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleRequest) ProtoMessage() {}

func (x *LocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleRequest.ProtoReflect.Descriptor instead.
func (*LocaleRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{16}
}

func (x *LocaleRequest) GetAssignments() []*locale.LocaleAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type TimezoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=Timezone,proto3" json:"Timezone,omitempty"` // String with timezone value. Format: [tz database](https://en.wikipedia.org/wiki/Tz_database) name, usually Area/City or Etc/GMT+3.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimezoneRequest) Reset() {
	*x = TimezoneRequest{}
	mi := &file_admin_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimezoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimezoneRequest) ProtoMessage() {}

func (x *TimezoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimezoneRequest.ProtoReflect.Descriptor instead.
func (*TimezoneRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{17}
}

func (x *TimezoneRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UserNotificationRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmName        string                   `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"`
	Notification  *notify.UserNotification `protobuf:"bytes,2,opt,name=Notification,proto3" json:"Notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationRequest) Reset() {
	*x = UserNotificationRequest{}
	mi := &file_admin_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationRequest) ProtoMessage() {}

func (x *UserNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationRequest.ProtoReflect.Descriptor instead.
func (*UserNotificationRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{18}
}

func (x *UserNotificationRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *UserNotificationRequest) GetNotification() *notify.UserNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type Generation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Generation            int32                  `protobuf:"varint,1,opt,name=Generation,proto3" json:"Generation,omitempty"`
	Date                  string                 `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	NixosVersion          string                 `protobuf:"bytes,3,opt,name=NixosVersion,proto3" json:"NixosVersion,omitempty"`
	KernelVersion         string                 `protobuf:"bytes,4,opt,name=KernelVersion,proto3" json:"KernelVersion,omitempty"`
	ConfigurationRevision string                 `protobuf:"bytes,5,opt,name=ConfigurationRevision,proto3" json:"ConfigurationRevision,omitempty"`
	Specialisations       []string               `protobuf:"bytes,6,rep,name=Specialisations,proto3" json:"Specialisations,omitempty"`
	Current               bool                   `protobuf:"varint,7,opt,name=Current,proto3" json:"Current,omitempty"`
	StorePath             string                 `protobuf:"bytes,8,opt,name=StorePath,proto3" json:"StorePath,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_admin_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{19}
}

func (x *Generation) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Generation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Generation) GetNixosVersion() string {
	if x != nil {
		return x.NixosVersion
	}
	return ""
}

func (x *Generation) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *Generation) GetConfigurationRevision() string {
	if x != nil {
		return x.ConfigurationRevision
	}
	return ""
}

func (x *Generation) GetSpecialisations() []string {
	if x != nil {
		return x.Specialisations
	}
	return nil
}

func (x *Generation) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *Generation) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

type ListGenerationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Generation          `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenerationsResponse) Reset() {
	*x = ListGenerationsResponse{}
	mi := &file_admin_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenerationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenerationsResponse) ProtoMessage() {}

func (x *ListGenerationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenerationsResponse.ProtoReflect.Descriptor instead.
func (*ListGenerationsResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListGenerationsResponse) GetList() []*Generation {
	if x != nil {
		return x.List
	}
	return nil
}

type SetGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*SetGenerationRequest_Cachix
	Update        isSetGenerationRequest_Update `protobuf_oneof:"Update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGenerationRequest) Reset() {
	*x = SetGenerationRequest{}
	mi := &file_admin_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGenerationRequest) ProtoMessage() {}

func (x *SetGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGenerationRequest.ProtoReflect.Descriptor instead.
func (*SetGenerationRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{21}
}

func (x *SetGenerationRequest) GetUpdate() isSetGenerationRequest_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SetGenerationRequest) GetCachix() *Cachix {
	if x != nil {
		if x, ok := x.Update.(*SetGenerationRequest_Cachix); ok {
			return x.Cachix
		}
	}
	return nil
}

type isSetGenerationRequest_Update interface {
	isSetGenerationRequest_Update()
}

type SetGenerationRequest_Cachix struct {
	Cachix *Cachix `protobuf:"bytes,1,opt,name=Cachix,proto3,oneof"`
}

func (*SetGenerationRequest_Cachix) isSetGenerationRequest_Update() {}

type Cachix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=Pin,proto3" json:"Pin,omitempty"`
	CachixHost    *string                `protobuf:"bytes,2,opt,name=CachixHost,proto3,oneof" json:"CachixHost,omitempty"` // API url for cachix
	Cache         string                 `protobuf:"bytes,3,opt,name=Cache,proto3" json:"Cache,omitempty"`
	Token         *string                `protobuf:"bytes,4,opt,name=Token,proto3,oneof" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cachix) Reset() {
	*x = Cachix{}
	mi := &file_admin_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cachix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cachix) ProtoMessage() {}

func (x *Cachix) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cachix.ProtoReflect.Descriptor instead.
func (*Cachix) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{22}
}

func (x *Cachix) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Cachix) GetCachixHost() string {
	if x != nil && x.CachixHost != nil {
		return *x.CachixHost
	}
	return ""
}

func (x *Cachix) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *Cachix) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type SetGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      bool                   `protobuf:"varint,1,opt,name=Finished,proto3" json:"Finished,omitempty"`
	Output        *string                `protobuf:"bytes,2,opt,name=Output,proto3,oneof" json:"Output,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=Error,proto3,oneof" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGenerationResponse) Reset() {
	*x = SetGenerationResponse{}
	mi := &file_admin_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGenerationResponse) ProtoMessage() {}

func (x *SetGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGenerationResponse.ProtoReflect.Descriptor instead.
func (*SetGenerationResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{23}
}

func (x *SetGenerationResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *SetGenerationResponse) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *SetGenerationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\x05admin\x1a\x11stats/stats.proto\x1a\x13locale/locale.proto\x1a\x15systemd/systemd.proto\x1a\x13notify/notify.proto\"o\n" +
	"\x0fTransportConfig\x12\x1a\n" +
	"\bProtocol\x18\x01 \x01(\tR\bProtocol\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x12\x12\n" +
	"\x04Port\x18\x03 \x01(\tR\x04Port\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\"\xb2\x01\n" +
	"\x0fRegistryRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Parent\x18\x02 \x01(\tR\x06Parent\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\rR\x04Type\x124\n" +
	"\tTransport\x18\x04 \x01(\v2\x16.admin.TransportConfigR\tTransport\x12)\n" +
	"\x05State\x18\x05 \x01(\v2\x13.systemd.UnitStatusR\x05State\"7\n" +
	"\x10RegistryResponse\x12\x19\n" +
	"\x05Error\x18\x01 \x01(\tH\x00R\x05Error\x88\x01\x01B\b\n" +
	"\x06_Error\"j\n" +
	"\x12ApplicationRequest\x12\x18\n" +
	"\aAppName\x18\x01 \x01(\tR\aAppName\x12\x1b\n" +
	"\x06VmName\x18\x02 \x01(\tH\x00R\x06VmName\x88\x01\x01\x12\x12\n" +
	"\x04Args\x18\x03 \x03(\tR\x04ArgsB\t\n" +
	"\a_VmName\"&\n" +
	"\fStatsRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\"(\n" +
	"\x0eStartVMRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\"O\n" +
	"\x13StartServiceRequest\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x12\x16\n" +
	"\x06VmName\x18\x02 \x01(\tR\x06VmName\"/\n" +
	"\rStartResponse\x12\x1e\n" +
	"\n" +
	"registryId\x18\x01 \x01(\tR\n" +
	"registryId\"Q\n" +
	"\x13ApplicationResponse\x12\x1c\n" +
	"\tCmdStatus\x18\x01 \x01(\tR\tCmdStatus\x12\x1c\n" +
	"\tAppStatus\x18\x02 \x01(\tR\tAppStatus\"G\n" +
	"\x11UnitStatusRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\x12\x1a\n" +
	"\bUnitName\x18\x02 \x01(\tR\bUnitName\"J\n" +
	"\x12PolicyQueryRequest\x12\x14\n" +
	"\x05Query\x18\x01 \x01(\tR\x05Query\x12\x1e\n" +
	"\n" +
	"PolicyPath\x18\x02 \x01(\tR\n" +
	"PolicyPath\"-\n" +
	"\x13PolicyQueryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\a\n" +
	"\x05Empty\"\x94\x02\n" +
	"\rQueryListItem\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1a\n" +
	"\bVmStatus\x18\x03 \x01(\tR\bVmStatus\x12\x1e\n" +
	"\n" +
	"TrustLevel\x18\x04 \x01(\tR\n" +
	"TrustLevel\x12\x16\n" +
	"\x06VmType\x18\x05 \x01(\tR\x06VmType\x12 \n" +
	"\vServiceType\x18\x06 \x01(\tR\vServiceType\x12\x1b\n" +
	"\x06VmName\x18\a \x01(\tH\x00R\x06VmName\x88\x01\x01\x12!\n" +
	"\tAgentName\x18\b \x01(\tH\x01R\tAgentName\x88\x01\x01B\t\n" +
	"\a_VmNameB\f\n" +
	"\n" +
	"_AgentName\"=\n" +
	"\x11QueryListResponse\x12(\n" +
	"\x04List\x18\x01 \x03(\v2\x14.admin.QueryListItemR\x04List\"\xdd\x01\n" +
	"\tWatchItem\x124\n" +
	"\aInitial\x18\x01 \x01(\v2\x18.admin.QueryListResponseH\x00R\aInitial\x12,\n" +
	"\x05Added\x18\x02 \x01(\v2\x14.admin.QueryListItemH\x00R\x05Added\x120\n" +
	"\aUpdated\x18\x03 \x01(\v2\x14.admin.QueryListItemH\x00R\aUpdated\x120\n" +
	"\aRemoved\x18\x04 \x01(\v2\x14.admin.QueryListItemH\x00R\aRemovedB\b\n" +
	"\x06Status\"K\n" +
	"\rLocaleRequest\x12:\n" +
	"\vassignments\x18\x01 \x03(\v2\x18.locale.LocaleAssignmentR\vassignments\"-\n" +
	"\x0fTimezoneRequest\x12\x1a\n" +
	"\bTimezone\x18\x01 \x01(\tR\bTimezone\"o\n" +
	"\x17UserNotificationRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\x12<\n" +
	"\fNotification\x18\x02 \x01(\v2\x18.notify.UserNotificationR\fNotification\"\xa2\x02\n" +
	"\n" +
	"Generation\x12\x1e\n" +
	"\n" +
	"Generation\x18\x01 \x01(\x05R\n" +
	"Generation\x12\x12\n" +
	"\x04Date\x18\x02 \x01(\tR\x04Date\x12\"\n" +
	"\fNixosVersion\x18\x03 \x01(\tR\fNixosVersion\x12$\n" +
	"\rKernelVersion\x18\x04 \x01(\tR\rKernelVersion\x124\n" +
	"\x15ConfigurationRevision\x18\x05 \x01(\tR\x15ConfigurationRevision\x12(\n" +
	"\x0fSpecialisations\x18\x06 \x03(\tR\x0fSpecialisations\x12\x18\n" +
	"\aCurrent\x18\a \x01(\bR\aCurrent\x12\x1c\n" +
	"\tStorePath\x18\b \x01(\tR\tStorePath\"@\n" +
	"\x17ListGenerationsResponse\x12%\n" +
	"\x04List\x18\x01 \x03(\v2\x11.admin.GenerationR\x04List\"I\n" +
	"\x14SetGenerationRequest\x12'\n" +
	"\x06Cachix\x18\x01 \x01(\v2\r.admin.CachixH\x00R\x06CachixB\b\n" +
	"\x06Update\"\x89\x01\n" +
	"\x06Cachix\x12\x10\n" +
	"\x03Pin\x18\x01 \x01(\tR\x03Pin\x12#\n" +
	"\n" +
	"CachixHost\x18\x02 \x01(\tH\x00R\n" +
	"CachixHost\x88\x01\x01\x12\x14\n" +
	"\x05Cache\x18\x03 \x01(\tR\x05Cache\x12\x19\n" +
	"\x05Token\x18\x04 \x01(\tH\x01R\x05Token\x88\x01\x01B\r\n" +
	"\v_CachixHostB\b\n" +
	"\x06_Token\"\x80\x01\n" +
	"\x15SetGenerationResponse\x12\x1a\n" +
	"\bFinished\x18\x01 \x01(\bR\bFinished\x12\x1b\n" +
	"\x06Output\x18\x02 \x01(\tH\x00R\x06Output\x88\x01\x01\x12\x19\n" +
	"\x05Error\x18\x03 \x01(\tH\x01R\x05Error\x88\x01\x01B\t\n" +
	"\a_OutputB\b\n" +
	"\x06_Error2\x87\n" +
	"\n" +
	"\fAdminService\x12D\n" +
	"\x0fRegisterService\x12\x16.admin.RegistryRequest\x1a\x17.admin.RegistryResponse\"\x00\x12E\n" +
	"\x10StartApplication\x12\x19.admin.ApplicationRequest\x1a\x14.admin.StartResponse\"\x00\x128\n" +
	"\aStartVM\x12\x15.admin.StartVMRequest\x1a\x14.admin.StartResponse\"\x00\x12B\n" +
	"\fStartService\x12\x1a.admin.StartServiceRequest\x1a\x14.admin.StartResponse\"\x00\x12K\n" +
	"\x10PauseApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x12L\n" +
	"\x11ResumeApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x12J\n" +
	"\x0fStopApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x121\n" +
	"\tSetLocale\x12\x14.admin.LocaleRequest\x1a\f.admin.Empty\"\x00\x125\n" +
	"\vSetTimezone\x12\x16.admin.TimezoneRequest\x1a\f.admin.Empty\"\x00\x12(\n" +
	"\bPoweroff\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12&\n" +
	"\x06Reboot\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12'\n" +
	"\aSuspend\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12&\n" +
	"\x06Wakeup\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12@\n" +
	"\rGetUnitStatus\x12\x18.admin.UnitStatusRequest\x1a\x13.systemd.UnitStatus\"\x00\x127\n" +
	"\bGetStats\x12\x13.admin.StatsRequest\x1a\x14.stats.StatsResponse\"\x00\x125\n" +
	"\tQueryList\x12\f.admin.Empty\x1a\x18.admin.QueryListResponse\"\x00\x12+\n" +
	"\x05Watch\x12\f.admin.Empty\x1a\x10.admin.WatchItem\"\x000\x01\x12A\n" +
	"\x0fListGenerations\x12\f.admin.Empty\x1a\x1e.admin.ListGenerationsResponse\"\x00\x12N\n" +
	"\rSetGeneration\x12\x1b.admin.SetGenerationRequest\x1a\x1c.admin.SetGenerationResponse\"\x000\x01\x12>\n" +
	"\n" +
	"NotifyUser\x12\x1e.admin.UserNotificationRequest\x1a\x0e.notify.Status\"\x00\x12F\n" +
	"\vPolicyQuery\x12\x19.admin.PolicyQueryRequest\x1a\x1a.admin.PolicyQueryResponse\"\x00B\x18Z\x16givc/modules/api/adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_admin_admin_proto_goTypes = []any{
	(*TransportConfig)(nil),         // 0: admin.TransportConfig
	(*RegistryRequest)(nil),         // 1: admin.RegistryRequest
	(*RegistryResponse)(nil),        // 2: admin.RegistryResponse
	(*ApplicationRequest)(nil),      // 3: admin.ApplicationRequest
	(*StatsRequest)(nil),            // 4: admin.StatsRequest
	(*StartVMRequest)(nil),          // 5: admin.StartVMRequest
	(*StartServiceRequest)(nil),     // 6: admin.StartServiceRequest
	(*StartResponse)(nil),           // 7: admin.StartResponse
	(*ApplicationResponse)(nil),     // 8: admin.ApplicationResponse
	(*UnitStatusRequest)(nil),       // 9: admin.UnitStatusRequest
	(*PolicyQueryRequest)(nil),      // 10: admin.PolicyQueryRequest
	(*PolicyQueryResponse)(nil),     // 11: admin.PolicyQueryResponse
	(*Empty)(nil),                   // 12: admin.Empty
	(*QueryListItem)(nil),           // 13: admin.QueryListItem
	(*QueryListResponse)(nil),       // 14: admin.QueryListResponse
	(*WatchItem)(nil),               // 15: admin.WatchItem
	(*LocaleRequest)(nil),           // 16: admin.LocaleRequest
	(*TimezoneRequest)(nil),         // 17: admin.TimezoneRequest
	(*UserNotificationRequest)(nil), // 18: admin.UserNotificationRequest
	(*Generation)(nil),              // 19: admin.Generation
	(*ListGenerationsResponse)(nil), // 20: admin.ListGenerationsResponse
	(*SetGenerationRequest)(nil),    // 21: admin.SetGenerationRequest
	(*Cachix)(nil),                  // 22: admin.Cachix
	(*SetGenerationResponse)(nil),   // 23: admin.SetGenerationResponse
	(*systemd.UnitStatus)(nil),      // 24: systemd.UnitStatus
	(*locale.LocaleAssignment)(nil), // 25: locale.LocaleAssignment
	(*notify.UserNotification)(nil), // 26: notify.UserNotification
	(*stats.StatsResponse)(nil),     // 27: stats.StatsResponse
	(*notify.Status)(nil),           // 28: notify.Status
}
var file_admin_admin_proto_depIdxs = []int32{
	0,  // 0: admin.RegistryRequest.Transport:type_name -> admin.TransportConfig
	24, // 1: admin.RegistryRequest.State:type_name -> systemd.UnitStatus
	13, // 2: admin.QueryListResponse.List:type_name -> admin.QueryListItem
	14, // 3: admin.WatchItem.Initial:type_name -> admin.QueryListResponse
	13, // 4: admin.WatchItem.Added:type_name -> admin.QueryListItem
	13, // 5: admin.WatchItem.Updated:type_name -> admin.QueryListItem
	13, // 6: admin.WatchItem.Removed:type_name -> admin.QueryListItem
	25, // 7: admin.LocaleRequest.assignments:type_name -> locale.LocaleAssignment
	26, // 8: admin.UserNotificationRequest.Notification:type_name -> notify.UserNotification
	19, // 9: admin.ListGenerationsResponse.List:type_name -> admin.Generation
	22, // 10: admin.SetGenerationRequest.Cachix:type_name -> admin.Cachix
	1,  // 11: admin.AdminService.RegisterService:input_type -> admin.RegistryRequest
	3,  // 12: admin.AdminService.StartApplication:input_type -> admin.ApplicationRequest
	5,  // 13: admin.AdminService.StartVM:input_type -> admin.StartVMRequest
	6,  // 14: admin.AdminService.StartService:input_type -> admin.StartServiceRequest
	3,  // 15: admin.AdminService.PauseApplication:input_type -> admin.ApplicationRequest
	3,  // 16: admin.AdminService.ResumeApplication:input_type -> admin.ApplicationRequest
	3,  // 17: admin.AdminService.StopApplication:input_type -> admin.ApplicationRequest
	16, // 18: admin.AdminService.SetLocale:input_type -> admin.LocaleRequest
	17, // 19: admin.AdminService.SetTimezone:input_type -> admin.TimezoneRequest
	12, // 20: admin.AdminService.Poweroff:input_type -> admin.Empty
	12, // 21: admin.AdminService.Reboot:input_type -> admin.Empty
	12, // 22: admin.AdminService.Suspend:input_type -> admin.Empty
	12, // 23: admin.AdminService.Wakeup:input_type -> admin.Empty
	9,  // 24: admin.AdminService.GetUnitStatus:input_type -> admin.UnitStatusRequest
	4,  // 25: admin.AdminService.GetStats:input_type -> admin.StatsRequest
	12, // 26: admin.AdminService.QueryList:input_type -> admin.Empty
	12, // 27: admin.AdminService.Watch:input_type -> admin.Empty
	12, // 28: admin.AdminService.ListGenerations:input_type -> admin.Empty
	21, // 29: admin.AdminService.SetGeneration:input_type -> admin.SetGenerationRequest
	18, // 30: admin.AdminService.NotifyUser:input_type -> admin.UserNotificationRequest
	10, // 31: admin.AdminService.PolicyQuery:input_type -> admin.PolicyQueryRequest
	2,  // 32: admin.AdminService.RegisterService:output_type -> admin.RegistryResponse
	7,  // 33: admin.AdminService.StartApplication:output_type -> admin.StartResponse
	7,  // 34: admin.AdminService.StartVM:output_type -> admin.StartResponse
	7,  // 35: admin.AdminService.StartService:output_type -> admin.StartResponse
	8,  // 36: admin.AdminService.PauseApplication:output_type -> admin.ApplicationResponse
	8,  // 37: admin.AdminService.ResumeApplication:output_type -> admin.ApplicationResponse
	8,  // 38: admin.AdminService.StopApplication:output_type -> admin.ApplicationResponse
	12, // 39: admin.AdminService.SetLocale:output_type -> admin.Empty
	12, // 40: admin.AdminService.SetTimezone:output_type -> admin.Empty
	12, // 41: admin.AdminService.Poweroff:output_type -> admin.Empty
	12, // 42: admin.AdminService.Reboot:output_type -> admin.Empty
	12, // 43: admin.AdminService.Suspend:output_type -> admin.Empty
	12, // 44: admin.AdminService.Wakeup:output_type -> admin.Empty
	24, // 45: admin.AdminService.GetUnitStatus:output_type -> systemd.UnitStatus
	27, // 46: admin.AdminService.GetStats:output_type -> stats.StatsResponse
	14, // 47: admin.AdminService.QueryList:output_type -> admin.QueryListResponse
	15, // 48: admin.AdminService.Watch:output_type -> admin.WatchItem
	20, // 49: admin.AdminService.ListGenerations:output_type -> admin.ListGenerationsResponse
	23, // 50: admin.AdminService.SetGeneration:output_type -> admin.SetGenerationResponse
	28, // 51: admin.AdminService.NotifyUser:output_type -> notify.Status
	11, // 52: admin.AdminService.PolicyQuery:output_type -> admin.PolicyQueryResponse
	32, // [32:53] is the sub-list for method output_type
	11, // [11:32] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	file_admin_admin_proto_msgTypes[2].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[3].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[13].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[15].OneofWrappers = []any{
		(*WatchItem_Initial)(nil),
		(*WatchItem_Added)(nil),
		(*WatchItem_Updated)(nil),
		(*WatchItem_Removed)(nil),
	}
	file_admin_admin_proto_msgTypes[21].OneofWrappers = []any{
		(*SetGenerationRequest_Cachix)(nil),
	}
	file_admin_admin_proto_msgTypes[22].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
