// SPDX-FileCopyrightText: 2024-2026 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: admin/admin.proto

package admin

import (
	locale "givc/modules/api/locale"
	stats "givc/modules/api/stats"
	systemd "givc/modules/api/systemd"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=Protocol,proto3" json:"Protocol,omitempty"` // Protocol identifier, one of tcp, vsock, unix
	Address       string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`   // IPv4 address, vsock CID, or unix socket path
	Port          string                 `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`         // Port number
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`         // Host name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TransportConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TransportConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransportConfig) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *TransportConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`           // Component name for registry entry
	Parent        string                 `protobuf:"bytes,2,opt,name=Parent,proto3" json:"Parent,omitempty"`       // Parent component identifier (registry name)
	Type          uint32                 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`          // Component type
	Transport     *TransportConfig       `protobuf:"bytes,4,opt,name=Transport,proto3" json:"Transport,omitempty"` // TransportConfig
	State         *systemd.UnitStatus    `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`         // Unit status of the component (systemd)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRequest) Reset() {
	*x = RegistryRequest{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRequest) ProtoMessage() {}

func (x *RegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRequest.ProtoReflect.Descriptor instead.
func (*RegistryRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *RegistryRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RegistryRequest) GetTransport() *TransportConfig {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *RegistryRequest) GetState() *systemd.UnitStatus {
	if x != nil {
		return x.State
	}
	return nil
}

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error,proto3,oneof" json:"Error,omitempty"` // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`     // Application name
	VmName        *string                `protobuf:"bytes,2,opt,name=VmName,proto3,oneof" json:"VmName,omitempty"` // Name of the VM hosting the application
	Args          []string               `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`           // Application arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationRequest) Reset() {
	*x = ApplicationRequest{}
	mi := &file_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationRequest) ProtoMessage() {}

func (x *ApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationRequest.ProtoReflect.Descriptor instead.
func (*ApplicationRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApplicationRequest) GetVmName() string {
	if x != nil && x.VmName != nil {
		return *x.VmName
	}
	return ""
}

func (x *ApplicationRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"` // VM name to query status information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *StatsRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"` // Name of the VM to start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *StartVMRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"` // Name of the service to start
	VmName        string                 `protobuf:"bytes,2,opt,name=VmName,proto3" json:"VmName,omitempty"`           // Name of the VM hosting service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *StartServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StartServiceRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryId    string                 `protobuf:"bytes,1,opt,name=registryId,proto3" json:"registryId,omitempty"` // Registry ID for newly started app, service or vm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *StartResponse) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

type ApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdStatus     string                 `protobuf:"bytes,1,opt,name=CmdStatus,proto3" json:"CmdStatus,omitempty"` // Status of the RPC command
	AppStatus     string                 `protobuf:"bytes,2,opt,name=AppStatus,proto3" json:"AppStatus,omitempty"` // Status of the application
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationResponse) Reset() {
	*x = ApplicationResponse{}
	mi := &file_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationResponse) ProtoMessage() {}

func (x *ApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationResponse.ProtoReflect.Descriptor instead.
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ApplicationResponse) GetCmdStatus() string {
	if x != nil {
		return x.CmdStatus
	}
	return ""
}

func (x *ApplicationResponse) GetAppStatus() string {
	if x != nil {
		return x.AppStatus
	}
	return ""
}

type UnitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=VmName,proto3" json:"VmName,omitempty"`     // Name of the VM hosting the unit
	UnitName      string                 `protobuf:"bytes,2,opt,name=UnitName,proto3" json:"UnitName,omitempty"` // Name of the unit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitStatusRequest) Reset() {
	*x = UnitStatusRequest{}
	mi := &file_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitStatusRequest) ProtoMessage() {}

func (x *UnitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitStatusRequest.ProtoReflect.Descriptor instead.
func (*UnitStatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UnitStatusRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *UnitStatusRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{10}
}

type QueryListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                 // Name of the unit
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`   // Description of the unit
	VmStatus      string                 `protobuf:"bytes,3,opt,name=VmStatus,proto3" json:"VmStatus,omitempty"`         // Status of the VM hosting the unit
	TrustLevel    string                 `protobuf:"bytes,4,opt,name=TrustLevel,proto3" json:"TrustLevel,omitempty"`     // Trust Level (future use)
	VmType        string                 `protobuf:"bytes,5,opt,name=VmType,proto3" json:"VmType,omitempty"`             // Type of the VM (future use)
	ServiceType   string                 `protobuf:"bytes,6,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"`   // Type of the service (future use)
	VmName        *string                `protobuf:"bytes,7,opt,name=VmName,proto3,oneof" json:"VmName,omitempty"`       // Name of the VM to query; None for host running services
	AgentName     *string                `protobuf:"bytes,8,opt,name=AgentName,proto3,oneof" json:"AgentName,omitempty"` // Name of the managing agent; None for agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListItem) Reset() {
	*x = QueryListItem{}
	mi := &file_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListItem) ProtoMessage() {}

func (x *QueryListItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListItem.ProtoReflect.Descriptor instead.
func (*QueryListItem) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *QueryListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QueryListItem) GetVmStatus() string {
	if x != nil {
		return x.VmStatus
	}
	return ""
}

func (x *QueryListItem) GetTrustLevel() string {
	if x != nil {
		return x.TrustLevel
	}
	return ""
}

func (x *QueryListItem) GetVmType() string {
	if x != nil {
		return x.VmType
	}
	return ""
}

func (x *QueryListItem) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *QueryListItem) GetVmName() string {
	if x != nil && x.VmName != nil {
		return *x.VmName
	}
	return ""
}

func (x *QueryListItem) GetAgentName() string {
	if x != nil && x.AgentName != nil {
		return *x.AgentName
	}
	return ""
}

type QueryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*QueryListItem       `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // List of query responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListResponse) Reset() {
	*x = QueryListResponse{}
	mi := &file_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListResponse) ProtoMessage() {}

func (x *QueryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListResponse.ProtoReflect.Descriptor instead.
func (*QueryListResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *QueryListResponse) GetList() []*QueryListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type WatchItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*WatchItem_Initial
	//	*WatchItem_Added
	//	*WatchItem_Updated
	//	*WatchItem_Removed
	Status        isWatchItem_Status `protobuf_oneof:"Status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItem) Reset() {
	*x = WatchItem{}
	mi := &file_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItem) ProtoMessage() {}

func (x *WatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItem.ProtoReflect.Descriptor instead.
func (*WatchItem) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *WatchItem) GetStatus() isWatchItem_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WatchItem) GetInitial() *QueryListResponse {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Initial); ok {
			return x.Initial
		}
	}
	return nil
}

func (x *WatchItem) GetAdded() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Added); ok {
			return x.Added
		}
	}
	return nil
}

func (x *WatchItem) GetUpdated() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *WatchItem) GetRemoved() *QueryListItem {
	if x != nil {
		if x, ok := x.Status.(*WatchItem_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

type isWatchItem_Status interface {
	isWatchItem_Status()
}

type WatchItem_Initial struct {
	Initial *QueryListResponse `protobuf:"bytes,1,opt,name=Initial,proto3,oneof"`
}

type WatchItem_Added struct {
	Added *QueryListItem `protobuf:"bytes,2,opt,name=Added,proto3,oneof"`
}

type WatchItem_Updated struct {
	Updated *QueryListItem `protobuf:"bytes,3,opt,name=Updated,proto3,oneof"`
}

type WatchItem_Removed struct {
	Removed *QueryListItem `protobuf:"bytes,4,opt,name=Removed,proto3,oneof"`
}

func (*WatchItem_Initial) isWatchItem_Status() {}

func (*WatchItem_Added) isWatchItem_Status() {}

func (*WatchItem_Updated) isWatchItem_Status() {}

func (*WatchItem_Removed) isWatchItem_Status() {}

type LocaleRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Assignments   []*locale.LocaleAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"` // List of locale assignments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleRequest) Reset() {
	*x = LocaleRequest{}
	mi := &file_admin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleRequest) ProtoMessage() {}

func (x *LocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleRequest.ProtoReflect.Descriptor instead.
func (*LocaleRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *LocaleRequest) GetAssignments() []*locale.LocaleAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type TimezoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=Timezone,proto3" json:"Timezone,omitempty"` // String with timezone value. Format: [tz database](https://en.wikipedia.org/wiki/Tz_database) name, usually Area/City or Etc/GMT+3.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimezoneRequest) Reset() {
	*x = TimezoneRequest{}
	mi := &file_admin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimezoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimezoneRequest) ProtoMessage() {}

func (x *TimezoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimezoneRequest.ProtoReflect.Descriptor instead.
func (*TimezoneRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *TimezoneRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\x05admin\x1a\x11stats/stats.proto\x1a\x13locale/locale.proto\x1a\x15systemd/systemd.proto\"o\n" +
	"\x0fTransportConfig\x12\x1a\n" +
	"\bProtocol\x18\x01 \x01(\tR\bProtocol\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x12\x12\n" +
	"\x04Port\x18\x03 \x01(\tR\x04Port\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\"\xb2\x01\n" +
	"\x0fRegistryRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Parent\x18\x02 \x01(\tR\x06Parent\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\rR\x04Type\x124\n" +
	"\tTransport\x18\x04 \x01(\v2\x16.admin.TransportConfigR\tTransport\x12)\n" +
	"\x05State\x18\x05 \x01(\v2\x13.systemd.UnitStatusR\x05State\"7\n" +
	"\x10RegistryResponse\x12\x19\n" +
	"\x05Error\x18\x01 \x01(\tH\x00R\x05Error\x88\x01\x01B\b\n" +
	"\x06_Error\"j\n" +
	"\x12ApplicationRequest\x12\x18\n" +
	"\aAppName\x18\x01 \x01(\tR\aAppName\x12\x1b\n" +
	"\x06VmName\x18\x02 \x01(\tH\x00R\x06VmName\x88\x01\x01\x12\x12\n" +
	"\x04Args\x18\x03 \x03(\tR\x04ArgsB\t\n" +
	"\a_VmName\"&\n" +
	"\fStatsRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\"(\n" +
	"\x0eStartVMRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\"O\n" +
	"\x13StartServiceRequest\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x12\x16\n" +
	"\x06VmName\x18\x02 \x01(\tR\x06VmName\"/\n" +
	"\rStartResponse\x12\x1e\n" +
	"\n" +
	"registryId\x18\x01 \x01(\tR\n" +
	"registryId\"Q\n" +
	"\x13ApplicationResponse\x12\x1c\n" +
	"\tCmdStatus\x18\x01 \x01(\tR\tCmdStatus\x12\x1c\n" +
	"\tAppStatus\x18\x02 \x01(\tR\tAppStatus\"G\n" +
	"\x11UnitStatusRequest\x12\x16\n" +
	"\x06VmName\x18\x01 \x01(\tR\x06VmName\x12\x1a\n" +
	"\bUnitName\x18\x02 \x01(\tR\bUnitName\"\a\n" +
	"\x05Empty\"\x94\x02\n" +
	"\rQueryListItem\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1a\n" +
	"\bVmStatus\x18\x03 \x01(\tR\bVmStatus\x12\x1e\n" +
	"\n" +
	"TrustLevel\x18\x04 \x01(\tR\n" +
	"TrustLevel\x12\x16\n" +
	"\x06VmType\x18\x05 \x01(\tR\x06VmType\x12 \n" +
	"\vServiceType\x18\x06 \x01(\tR\vServiceType\x12\x1b\n" +
	"\x06VmName\x18\a \x01(\tH\x00R\x06VmName\x88\x01\x01\x12!\n" +
	"\tAgentName\x18\b \x01(\tH\x01R\tAgentName\x88\x01\x01B\t\n" +
	"\a_VmNameB\f\n" +
	"\n" +
	"_AgentName\"=\n" +
	"\x11QueryListResponse\x12(\n" +
	"\x04List\x18\x01 \x03(\v2\x14.admin.QueryListItemR\x04List\"\xdd\x01\n" +
	"\tWatchItem\x124\n" +
	"\aInitial\x18\x01 \x01(\v2\x18.admin.QueryListResponseH\x00R\aInitial\x12,\n" +
	"\x05Added\x18\x02 \x01(\v2\x14.admin.QueryListItemH\x00R\x05Added\x120\n" +
	"\aUpdated\x18\x03 \x01(\v2\x14.admin.QueryListItemH\x00R\aUpdated\x120\n" +
	"\aRemoved\x18\x04 \x01(\v2\x14.admin.QueryListItemH\x00R\aRemovedB\b\n" +
	"\x06Status\"K\n" +
	"\rLocaleRequest\x12:\n" +
	"\vassignments\x18\x01 \x03(\v2\x18.locale.LocaleAssignmentR\vassignments\"-\n" +
	"\x0fTimezoneRequest\x12\x1a\n" +
	"\bTimezone\x18\x01 \x01(\tR\bTimezone2\xec\a\n" +
	"\fAdminService\x12D\n" +
	"\x0fRegisterService\x12\x16.admin.RegistryRequest\x1a\x17.admin.RegistryResponse\"\x00\x12E\n" +
	"\x10StartApplication\x12\x19.admin.ApplicationRequest\x1a\x14.admin.StartResponse\"\x00\x128\n" +
	"\aStartVM\x12\x15.admin.StartVMRequest\x1a\x14.admin.StartResponse\"\x00\x12B\n" +
	"\fStartService\x12\x1a.admin.StartServiceRequest\x1a\x14.admin.StartResponse\"\x00\x12K\n" +
	"\x10PauseApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x12L\n" +
	"\x11ResumeApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x12J\n" +
	"\x0fStopApplication\x12\x19.admin.ApplicationRequest\x1a\x1a.admin.ApplicationResponse\"\x00\x121\n" +
	"\tSetLocale\x12\x14.admin.LocaleRequest\x1a\f.admin.Empty\"\x00\x125\n" +
	"\vSetTimezone\x12\x16.admin.TimezoneRequest\x1a\f.admin.Empty\"\x00\x12(\n" +
	"\bPoweroff\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12&\n" +
	"\x06Reboot\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12'\n" +
	"\aSuspend\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12&\n" +
	"\x06Wakeup\x12\f.admin.Empty\x1a\f.admin.Empty\"\x00\x12@\n" +
	"\rGetUnitStatus\x12\x18.admin.UnitStatusRequest\x1a\x13.systemd.UnitStatus\"\x00\x127\n" +
	"\bGetStats\x12\x13.admin.StatsRequest\x1a\x14.stats.StatsResponse\"\x00\x125\n" +
	"\tQueryList\x12\f.admin.Empty\x1a\x18.admin.QueryListResponse\"\x00\x12+\n" +
	"\x05Watch\x12\f.admin.Empty\x1a\x10.admin.WatchItem\"\x000\x01B\x18Z\x16givc/modules/api/adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_admin_admin_proto_goTypes = []any{
	(*TransportConfig)(nil),         // 0: admin.TransportConfig
	(*RegistryRequest)(nil),         // 1: admin.RegistryRequest
	(*RegistryResponse)(nil),        // 2: admin.RegistryResponse
	(*ApplicationRequest)(nil),      // 3: admin.ApplicationRequest
	(*StatsRequest)(nil),            // 4: admin.StatsRequest
	(*StartVMRequest)(nil),          // 5: admin.StartVMRequest
	(*StartServiceRequest)(nil),     // 6: admin.StartServiceRequest
	(*StartResponse)(nil),           // 7: admin.StartResponse
	(*ApplicationResponse)(nil),     // 8: admin.ApplicationResponse
	(*UnitStatusRequest)(nil),       // 9: admin.UnitStatusRequest
	(*Empty)(nil),                   // 10: admin.Empty
	(*QueryListItem)(nil),           // 11: admin.QueryListItem
	(*QueryListResponse)(nil),       // 12: admin.QueryListResponse
	(*WatchItem)(nil),               // 13: admin.WatchItem
	(*LocaleRequest)(nil),           // 14: admin.LocaleRequest
	(*TimezoneRequest)(nil),         // 15: admin.TimezoneRequest
	(*systemd.UnitStatus)(nil),      // 16: systemd.UnitStatus
	(*locale.LocaleAssignment)(nil), // 17: locale.LocaleAssignment
	(*stats.StatsResponse)(nil),     // 18: stats.StatsResponse
}
var file_admin_admin_proto_depIdxs = []int32{
	0,  // 0: admin.RegistryRequest.Transport:type_name -> admin.TransportConfig
	16, // 1: admin.RegistryRequest.State:type_name -> systemd.UnitStatus
	11, // 2: admin.QueryListResponse.List:type_name -> admin.QueryListItem
	12, // 3: admin.WatchItem.Initial:type_name -> admin.QueryListResponse
	11, // 4: admin.WatchItem.Added:type_name -> admin.QueryListItem
	11, // 5: admin.WatchItem.Updated:type_name -> admin.QueryListItem
	11, // 6: admin.WatchItem.Removed:type_name -> admin.QueryListItem
	17, // 7: admin.LocaleRequest.assignments:type_name -> locale.LocaleAssignment
	1,  // 8: admin.AdminService.RegisterService:input_type -> admin.RegistryRequest
	3,  // 9: admin.AdminService.StartApplication:input_type -> admin.ApplicationRequest
	5,  // 10: admin.AdminService.StartVM:input_type -> admin.StartVMRequest
	6,  // 11: admin.AdminService.StartService:input_type -> admin.StartServiceRequest
	3,  // 12: admin.AdminService.PauseApplication:input_type -> admin.ApplicationRequest
	3,  // 13: admin.AdminService.ResumeApplication:input_type -> admin.ApplicationRequest
	3,  // 14: admin.AdminService.StopApplication:input_type -> admin.ApplicationRequest
	14, // 15: admin.AdminService.SetLocale:input_type -> admin.LocaleRequest
	15, // 16: admin.AdminService.SetTimezone:input_type -> admin.TimezoneRequest
	10, // 17: admin.AdminService.Poweroff:input_type -> admin.Empty
	10, // 18: admin.AdminService.Reboot:input_type -> admin.Empty
	10, // 19: admin.AdminService.Suspend:input_type -> admin.Empty
	10, // 20: admin.AdminService.Wakeup:input_type -> admin.Empty
	9,  // 21: admin.AdminService.GetUnitStatus:input_type -> admin.UnitStatusRequest
	4,  // 22: admin.AdminService.GetStats:input_type -> admin.StatsRequest
	10, // 23: admin.AdminService.QueryList:input_type -> admin.Empty
	10, // 24: admin.AdminService.Watch:input_type -> admin.Empty
	2,  // 25: admin.AdminService.RegisterService:output_type -> admin.RegistryResponse
	7,  // 26: admin.AdminService.StartApplication:output_type -> admin.StartResponse
	7,  // 27: admin.AdminService.StartVM:output_type -> admin.StartResponse
	7,  // 28: admin.AdminService.StartService:output_type -> admin.StartResponse
	8,  // 29: admin.AdminService.PauseApplication:output_type -> admin.ApplicationResponse
	8,  // 30: admin.AdminService.ResumeApplication:output_type -> admin.ApplicationResponse
	8,  // 31: admin.AdminService.StopApplication:output_type -> admin.ApplicationResponse
	10, // 32: admin.AdminService.SetLocale:output_type -> admin.Empty
	10, // 33: admin.AdminService.SetTimezone:output_type -> admin.Empty
	10, // 34: admin.AdminService.Poweroff:output_type -> admin.Empty
	10, // 35: admin.AdminService.Reboot:output_type -> admin.Empty
	10, // 36: admin.AdminService.Suspend:output_type -> admin.Empty
	10, // 37: admin.AdminService.Wakeup:output_type -> admin.Empty
	16, // 38: admin.AdminService.GetUnitStatus:output_type -> systemd.UnitStatus
	18, // 39: admin.AdminService.GetStats:output_type -> stats.StatsResponse
	12, // 40: admin.AdminService.QueryList:output_type -> admin.QueryListResponse
	13, // 41: admin.AdminService.Watch:output_type -> admin.WatchItem
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	file_admin_admin_proto_msgTypes[2].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[3].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[11].OneofWrappers = []any{}
	file_admin_admin_proto_msgTypes[13].OneofWrappers = []any{
		(*WatchItem_Initial)(nil),
		(*WatchItem_Added)(nil),
		(*WatchItem_Updated)(nil),
		(*WatchItem_Removed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
