# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  run-checks:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: nix-checks-${{ matrix.arch }}
      cancel-in-progress: false
    strategy:
      matrix:
        include:
          - arch: "x86_64-linux"
            os: "ubuntu-latest"
          - arch: "aarch64-linux"
            os: "ubuntu-24.04-arm"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Platform
        run: uname -a
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          enable_kvm: true
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change
      - name: Check nix flake show runs successfully
        run: nix flake show --system ${{ matrix.arch }}
      - name: Run nix flake check
        run: |
          if [ "${{ matrix.arch }}" = "x86_64-linux" ]; then
            nix flake check --system ${{ matrix.arch }} --max-jobs 1
          else
            nix flake check --system ${{ matrix.arch }}
          fi
