# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: go-sectest
on:
    push:
        paths:
        - 'modules/**'
    pull_request:
        paths:
        - 'modules/**'
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install libudev-dev (for go-udev)
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Run Gosec Security Scanner
        uses: securego/gosec@bb17e422fc34bf4c0a2e5cab9d07dc45a68c040c # master
        with:
          args: '-exclude=G302,G204 -no-fail ./modules/...'
      - name: Run Go Tests
        run: go test -v ./modules/...
