// SPDX-FileCopyrightText: 2026 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: exec/exec.proto

package exec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exec_RunCommand_FullMethodName = "/exec.Exec/RunCommand"
)

// ExecClient is the client API for Exec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service to execute and manage subprocess commands
type ExecClient interface {
	// Execute a command and wait for it to complete
	RunCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandRequest, CommandResponse], error)
}

type execClient struct {
	cc grpc.ClientConnInterface
}

func NewExecClient(cc grpc.ClientConnInterface) ExecClient {
	return &execClient{cc}
}

func (c *execClient) RunCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandRequest, CommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Exec_ServiceDesc.Streams[0], Exec_RunCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandRequest, CommandResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Exec_RunCommandClient = grpc.BidiStreamingClient[CommandRequest, CommandResponse]

// ExecServer is the server API for Exec service.
// All implementations must embed UnimplementedExecServer
// for forward compatibility.
//
// Define the service to execute and manage subprocess commands
type ExecServer interface {
	// Execute a command and wait for it to complete
	RunCommand(grpc.BidiStreamingServer[CommandRequest, CommandResponse]) error
	mustEmbedUnimplementedExecServer()
}

// UnimplementedExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecServer struct{}

func (UnimplementedExecServer) RunCommand(grpc.BidiStreamingServer[CommandRequest, CommandResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedExecServer) mustEmbedUnimplementedExecServer() {}
func (UnimplementedExecServer) testEmbeddedByValue()              {}

// UnsafeExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecServer will
// result in compilation errors.
type UnsafeExecServer interface {
	mustEmbedUnimplementedExecServer()
}

func RegisterExecServer(s grpc.ServiceRegistrar, srv ExecServer) {
	// If the following call pancis, it indicates UnimplementedExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exec_ServiceDesc, srv)
}

func _Exec_RunCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecServer).RunCommand(&grpc.GenericServerStream[CommandRequest, CommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Exec_RunCommandServer = grpc.BidiStreamingServer[CommandRequest, CommandResponse]

// Exec_ServiceDesc is the grpc.ServiceDesc for Exec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exec.Exec",
	HandlerType: (*ExecServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunCommand",
			Handler:       _Exec_RunCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "exec/exec.proto",
}
