// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: exec/exec.proto

package exec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the request to execute a subprocess command
type StartCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`                                                                           // The shell command to execute
	Arguments        []string               `protobuf:"bytes,2,rep,name=Arguments,proto3" json:"Arguments,omitempty"`                                                                       // Arguments for the command
	WorkingDirectory *string                `protobuf:"bytes,3,opt,name=WorkingDirectory,proto3,oneof" json:"WorkingDirectory,omitempty"`                                                   // (Optional) Directory to execute the command in
	EnvVars          map[string]string      `protobuf:"bytes,4,rep,name=EnvVars,proto3" json:"EnvVars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // (Optional) Environment variables
	Stdin            []byte                 `protobuf:"bytes,5,opt,name=Stdin,proto3,oneof" json:"Stdin,omitempty"`                                                                         // Initial stdin sequence, if omitted -- standard input would be bound to /dev/null
	// Additional input could be supplied via `CommandRequest.Command.Stdin`
	// If all input planned to supplied this way, `StartCommand.Stdin` should be set as empty byte string
	Role          *string `protobuf:"bytes,6,opt,name=Role,proto3,oneof" json:"Role,omitempty"` // Role is actually a user name or security token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCommand) Reset() {
	*x = StartCommand{}
	mi := &file_exec_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCommand) ProtoMessage() {}

func (x *StartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCommand.ProtoReflect.Descriptor instead.
func (*StartCommand) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{0}
}

func (x *StartCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartCommand) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *StartCommand) GetWorkingDirectory() string {
	if x != nil && x.WorkingDirectory != nil {
		return *x.WorkingDirectory
	}
	return ""
}

func (x *StartCommand) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *StartCommand) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *StartCommand) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

type CommandIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=Eof,proto3" json:"Eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandIO) Reset() {
	*x = CommandIO{}
	mi := &file_exec_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandIO) ProtoMessage() {}

func (x *CommandIO) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandIO.ProtoReflect.Descriptor instead.
func (*CommandIO) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{1}
}

func (x *CommandIO) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandIO) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type SignalCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        int32                  `protobuf:"varint,1,opt,name=Signal,proto3" json:"Signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalCommand) Reset() {
	*x = SignalCommand{}
	mi := &file_exec_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalCommand) ProtoMessage() {}

func (x *SignalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalCommand.ProtoReflect.Descriptor instead.
func (*SignalCommand) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{2}
}

func (x *SignalCommand) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type StartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartedEvent) Reset() {
	*x = StartedEvent{}
	mi := &file_exec_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedEvent) ProtoMessage() {}

func (x *StartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedEvent.ProtoReflect.Descriptor instead.
func (*StartedEvent) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{3}
}

func (x *StartedEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type FinishedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    int32                  `protobuf:"varint,1,opt,name=ReturnCode,proto3" json:"ReturnCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishedEvent) Reset() {
	*x = FinishedEvent{}
	mi := &file_exec_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedEvent) ProtoMessage() {}

func (x *FinishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedEvent.ProtoReflect.Descriptor instead.
func (*FinishedEvent) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{4}
}

func (x *FinishedEvent) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandRequest_Start
	//	*CommandRequest_Stdin
	//	*CommandRequest_Signal
	Command       isCommandRequest_Command `protobuf_oneof:"Command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_exec_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{5}
}

func (x *CommandRequest) GetCommand() isCommandRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetStart() *StartCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CommandRequest) GetStdin() *CommandIO {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *CommandRequest) GetSignal() *SignalCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isCommandRequest_Command interface {
	isCommandRequest_Command()
}

type CommandRequest_Start struct {
	Start *StartCommand `protobuf:"bytes,1,opt,name=Start,proto3,oneof"`
}

type CommandRequest_Stdin struct {
	Stdin *CommandIO `protobuf:"bytes,2,opt,name=Stdin,proto3,oneof"`
}

type CommandRequest_Signal struct {
	Signal *SignalCommand `protobuf:"bytes,3,opt,name=Signal,proto3,oneof"`
}

func (*CommandRequest_Start) isCommandRequest_Command() {}

func (*CommandRequest_Stdin) isCommandRequest_Command() {}

func (*CommandRequest_Signal) isCommandRequest_Command() {}

type CommandRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=Agent,proto3" json:"Agent,omitempty"`
	Command       *CommandRequest        `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRelayRequest) Reset() {
	*x = CommandRelayRequest{}
	mi := &file_exec_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRelayRequest) ProtoMessage() {}

func (x *CommandRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRelayRequest.ProtoReflect.Descriptor instead.
func (*CommandRelayRequest) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{6}
}

func (x *CommandRelayRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CommandRelayRequest) GetCommand() *CommandRequest {
	if x != nil {
		return x.Command
	}
	return nil
}

type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CommandResponse_Stdout
	//	*CommandResponse_Stderr
	//	*CommandResponse_Started
	//	*CommandResponse_Finished
	Event         isCommandResponse_Event `protobuf_oneof:"Event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_exec_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResponse) GetEvent() isCommandResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CommandResponse) GetStdout() *CommandIO {
	if x != nil {
		if x, ok := x.Event.(*CommandResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *CommandResponse) GetStderr() *CommandIO {
	if x != nil {
		if x, ok := x.Event.(*CommandResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *CommandResponse) GetStarted() *StartedEvent {
	if x != nil {
		if x, ok := x.Event.(*CommandResponse_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *CommandResponse) GetFinished() *FinishedEvent {
	if x != nil {
		if x, ok := x.Event.(*CommandResponse_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

type isCommandResponse_Event interface {
	isCommandResponse_Event()
}

type CommandResponse_Stdout struct {
	Stdout *CommandIO `protobuf:"bytes,1,opt,name=Stdout,proto3,oneof"`
}

type CommandResponse_Stderr struct {
	Stderr *CommandIO `protobuf:"bytes,2,opt,name=Stderr,proto3,oneof"`
}

type CommandResponse_Started struct {
	Started *StartedEvent `protobuf:"bytes,3,opt,name=Started,proto3,oneof"`
}

type CommandResponse_Finished struct {
	Finished *FinishedEvent `protobuf:"bytes,4,opt,name=Finished,proto3,oneof"`
}

func (*CommandResponse_Stdout) isCommandResponse_Event() {}

func (*CommandResponse_Stderr) isCommandResponse_Event() {}

func (*CommandResponse_Started) isCommandResponse_Event() {}

func (*CommandResponse_Finished) isCommandResponse_Event() {}

var File_exec_exec_proto protoreflect.FileDescriptor

const file_exec_exec_proto_rawDesc = "" +
	"\n" +
	"\x0fexec/exec.proto\x12\x04exec\"\xca\x02\n" +
	"\fStartCommand\x12\x18\n" +
	"\aCommand\x18\x01 \x01(\tR\aCommand\x12\x1c\n" +
	"\tArguments\x18\x02 \x03(\tR\tArguments\x12/\n" +
	"\x10WorkingDirectory\x18\x03 \x01(\tH\x00R\x10WorkingDirectory\x88\x01\x01\x129\n" +
	"\aEnvVars\x18\x04 \x03(\v2\x1f.exec.StartCommand.EnvVarsEntryR\aEnvVars\x12\x19\n" +
	"\x05Stdin\x18\x05 \x01(\fH\x01R\x05Stdin\x88\x01\x01\x12\x17\n" +
	"\x04Role\x18\x06 \x01(\tH\x02R\x04Role\x88\x01\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_WorkingDirectoryB\b\n" +
	"\x06_StdinB\a\n" +
	"\x05_Role\"7\n" +
	"\tCommandIO\x12\x18\n" +
	"\aPayload\x18\x01 \x01(\fR\aPayload\x12\x10\n" +
	"\x03Eof\x18\x02 \x01(\bR\x03Eof\"'\n" +
	"\rSignalCommand\x12\x16\n" +
	"\x06Signal\x18\x01 \x01(\x05R\x06Signal\" \n" +
	"\fStartedEvent\x12\x10\n" +
	"\x03Pid\x18\x01 \x01(\x05R\x03Pid\"/\n" +
	"\rFinishedEvent\x12\x1e\n" +
	"\n" +
	"ReturnCode\x18\x01 \x01(\x05R\n" +
	"ReturnCode\"\x9f\x01\n" +
	"\x0eCommandRequest\x12*\n" +
	"\x05Start\x18\x01 \x01(\v2\x12.exec.StartCommandH\x00R\x05Start\x12'\n" +
	"\x05Stdin\x18\x02 \x01(\v2\x0f.exec.CommandIOH\x00R\x05Stdin\x12-\n" +
	"\x06Signal\x18\x03 \x01(\v2\x13.exec.SignalCommandH\x00R\x06SignalB\t\n" +
	"\aCommand\"[\n" +
	"\x13CommandRelayRequest\x12\x14\n" +
	"\x05Agent\x18\x01 \x01(\tR\x05Agent\x12.\n" +
	"\aCommand\x18\x02 \x01(\v2\x14.exec.CommandRequestR\aCommand\"\xd3\x01\n" +
	"\x0fCommandResponse\x12)\n" +
	"\x06Stdout\x18\x01 \x01(\v2\x0f.exec.CommandIOH\x00R\x06Stdout\x12)\n" +
	"\x06Stderr\x18\x02 \x01(\v2\x0f.exec.CommandIOH\x00R\x06Stderr\x12.\n" +
	"\aStarted\x18\x03 \x01(\v2\x12.exec.StartedEventH\x00R\aStarted\x121\n" +
	"\bFinished\x18\x04 \x01(\v2\x13.exec.FinishedEventH\x00R\bFinishedB\a\n" +
	"\x05Event2E\n" +
	"\x04Exec\x12=\n" +
	"\n" +
	"RunCommand\x12\x14.exec.CommandRequest\x1a\x15.exec.CommandResponse(\x010\x01B\bZ\x06./execb\x06proto3"

var (
	file_exec_exec_proto_rawDescOnce sync.Once
	file_exec_exec_proto_rawDescData []byte
)

func file_exec_exec_proto_rawDescGZIP() []byte {
	file_exec_exec_proto_rawDescOnce.Do(func() {
		file_exec_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_exec_proto_rawDesc), len(file_exec_exec_proto_rawDesc)))
	})
	return file_exec_exec_proto_rawDescData
}

var file_exec_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_exec_exec_proto_goTypes = []any{
	(*StartCommand)(nil),        // 0: exec.StartCommand
	(*CommandIO)(nil),           // 1: exec.CommandIO
	(*SignalCommand)(nil),       // 2: exec.SignalCommand
	(*StartedEvent)(nil),        // 3: exec.StartedEvent
	(*FinishedEvent)(nil),       // 4: exec.FinishedEvent
	(*CommandRequest)(nil),      // 5: exec.CommandRequest
	(*CommandRelayRequest)(nil), // 6: exec.CommandRelayRequest
	(*CommandResponse)(nil),     // 7: exec.CommandResponse
	nil,                         // 8: exec.StartCommand.EnvVarsEntry
}
var file_exec_exec_proto_depIdxs = []int32{
	8,  // 0: exec.StartCommand.EnvVars:type_name -> exec.StartCommand.EnvVarsEntry
	0,  // 1: exec.CommandRequest.Start:type_name -> exec.StartCommand
	1,  // 2: exec.CommandRequest.Stdin:type_name -> exec.CommandIO
	2,  // 3: exec.CommandRequest.Signal:type_name -> exec.SignalCommand
	5,  // 4: exec.CommandRelayRequest.Command:type_name -> exec.CommandRequest
	1,  // 5: exec.CommandResponse.Stdout:type_name -> exec.CommandIO
	1,  // 6: exec.CommandResponse.Stderr:type_name -> exec.CommandIO
	3,  // 7: exec.CommandResponse.Started:type_name -> exec.StartedEvent
	4,  // 8: exec.CommandResponse.Finished:type_name -> exec.FinishedEvent
	5,  // 9: exec.Exec.RunCommand:input_type -> exec.CommandRequest
	7,  // 10: exec.Exec.RunCommand:output_type -> exec.CommandResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_exec_exec_proto_init() }
func file_exec_exec_proto_init() {
	if File_exec_exec_proto != nil {
		return
	}
	file_exec_exec_proto_msgTypes[0].OneofWrappers = []any{}
	file_exec_exec_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandRequest_Start)(nil),
		(*CommandRequest_Stdin)(nil),
		(*CommandRequest_Signal)(nil),
	}
	file_exec_exec_proto_msgTypes[7].OneofWrappers = []any{
		(*CommandResponse_Stdout)(nil),
		(*CommandResponse_Stderr)(nil),
		(*CommandResponse_Started)(nil),
		(*CommandResponse_Finished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_exec_proto_rawDesc), len(file_exec_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_exec_proto_goTypes,
		DependencyIndexes: file_exec_exec_proto_depIdxs,
		MessageInfos:      file_exec_exec_proto_msgTypes,
	}.Build()
	File_exec_exec_proto = out.File
	file_exec_exec_proto_goTypes = nil
	file_exec_exec_proto_depIdxs = nil
}
