// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: policyagent/policyagent.proto

package policyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArchiveChunk  []byte                 `protobuf:"bytes,1,opt,name=archive_chunk,json=archiveChunk,proto3" json:"archive_chunk,omitempty"`
	ChangeSet     string                 `protobuf:"bytes,2,opt,name=change_set,json=changeSet,proto3" json:"change_set,omitempty"`
	OldRev        string                 `protobuf:"bytes,3,opt,name=old_rev,json=oldRev,proto3" json:"old_rev,omitempty"`
	NewRev        string                 `protobuf:"bytes,4,opt,name=new_rev,json=newRev,proto3" json:"new_rev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPolicyRequest) Reset() {
	*x = StreamPolicyRequest{}
	mi := &file_policyagent_policyagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPolicyRequest) ProtoMessage() {}

func (x *StreamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policyagent_policyagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPolicyRequest.ProtoReflect.Descriptor instead.
func (*StreamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policyagent_policyagent_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPolicyRequest) GetArchiveChunk() []byte {
	if x != nil {
		return x.ArchiveChunk
	}
	return nil
}

func (x *StreamPolicyRequest) GetChangeSet() string {
	if x != nil {
		return x.ChangeSet
	}
	return ""
}

func (x *StreamPolicyRequest) GetOldRev() string {
	if x != nil {
		return x.OldRev
	}
	return ""
}

func (x *StreamPolicyRequest) GetNewRev() string {
	if x != nil {
		return x.NewRev
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_policyagent_policyagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_policyagent_policyagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_policyagent_policyagent_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_policyagent_policyagent_proto protoreflect.FileDescriptor

const file_policyagent_policyagent_proto_rawDesc = "" +
	"\n" +
	"\x1dpolicyagent/policyagent.proto\x12\vpolicyagent\"\x8b\x01\n" +
	"\x13StreamPolicyRequest\x12#\n" +
	"\rarchive_chunk\x18\x01 \x01(\fR\farchiveChunk\x12\x1d\n" +
	"\n" +
	"change_set\x18\x02 \x01(\tR\tchangeSet\x12\x17\n" +
	"\aold_rev\x18\x03 \x01(\tR\x06oldRev\x12\x17\n" +
	"\anew_rev\x18\x04 \x01(\tR\x06newRev\" \n" +
	"\x06Status\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status2V\n" +
	"\vPolicyAgent\x12G\n" +
	"\fStreamPolicy\x12 .policyagent.StreamPolicyRequest\x1a\x13.policyagent.Status(\x01B\x1eZ\x1cgivc/modules/api/policyagentb\x06proto3"

var (
	file_policyagent_policyagent_proto_rawDescOnce sync.Once
	file_policyagent_policyagent_proto_rawDescData []byte
)

func file_policyagent_policyagent_proto_rawDescGZIP() []byte {
	file_policyagent_policyagent_proto_rawDescOnce.Do(func() {
		file_policyagent_policyagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policyagent_policyagent_proto_rawDesc), len(file_policyagent_policyagent_proto_rawDesc)))
	})
	return file_policyagent_policyagent_proto_rawDescData
}

var file_policyagent_policyagent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policyagent_policyagent_proto_goTypes = []any{
	(*StreamPolicyRequest)(nil), // 0: policyagent.StreamPolicyRequest
	(*Status)(nil),              // 1: policyagent.Status
}
var file_policyagent_policyagent_proto_depIdxs = []int32{
	0, // 0: policyagent.PolicyAgent.StreamPolicy:input_type -> policyagent.StreamPolicyRequest
	1, // 1: policyagent.PolicyAgent.StreamPolicy:output_type -> policyagent.Status
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_policyagent_policyagent_proto_init() }
func file_policyagent_policyagent_proto_init() {
	if File_policyagent_policyagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policyagent_policyagent_proto_rawDesc), len(file_policyagent_policyagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policyagent_policyagent_proto_goTypes,
		DependencyIndexes: file_policyagent_policyagent_proto_depIdxs,
		MessageInfos:      file_policyagent_policyagent_proto_msgTypes,
	}.Build()
	File_policyagent_policyagent_proto = out.File
	file_policyagent_policyagent_proto_goTypes = nil
	file_policyagent_policyagent_proto_depIdxs = nil
}
